"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ArrowDownIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M11.826 7a1 1 0 0 1 .76 1.65l-3.827 4.464a1 1 0 0 1-1.518 0L3.415 8.651A1 1 0 0 1 4.175 7h7.65zM7 7h2V3a1 1 0 0 0-2 0v4z"
  }))
});
ArrowDownIcon.displayName = 'ArrowDownIcon';
var _default = ArrowDownIcon;
exports.default = _default;