"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ArrowUpIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M4.174 9a1 1 0 0 1-.759-1.65l3.826-4.464a1 1 0 0 1 1.518 0l3.826 4.463A1 1 0 0 1 11.825 9h-7.65zM9 9H7v4a1 1 0 1 0 2 0V9z"
  }))
});
ArrowUpIcon.displayName = 'ArrowUpIcon';
var _default = ArrowUpIcon;
exports.default = _default;