"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ArrowLeftIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M9 4.174a1 1 0 0 0-1.65-.76L2.885 7.242a1 1 0 0 0 0 1.518l4.463 3.826A1 1 0 0 0 9 11.825V9h4a1 1 0 1 0 0-2H9V4.174z"
  }))
});
ArrowLeftIcon.displayName = 'ArrowLeftIcon';
var _default = ArrowLeftIcon;
exports.default = _default;