"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ArrowRightIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M7 4.197a1 1 0 0 1 1.657-.755l4.483 3.904a1 1 0 0 1-.014 1.521l-4.484 3.757A1 1 0 0 1 7 11.857v-7.66zM7 9V7H3a1 1 0 1 0 0 2h4z"
  }))
});
ArrowRightIcon.displayName = 'ArrowRightIcon';
var _default = ArrowRightIcon;
exports.default = _default;