"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var CameraIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM4 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"
  }), _react.default.createElement("path", {
    d: "M4 5a4 4 0 1 1 8 0H4z"
  }))
});
CameraIcon.displayName = 'CameraIcon';
var _default = CameraIcon;
exports.default = _default;