"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ChartLineIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M15.38 2.744a1.5 1.5 0 0 1 0 2.121l-6.818 6.818L5.5 8.62l-2.94 2.94A1.5 1.5 0 1 1 .44 9.439L5.5 4.38 8.562 7.44l4.696-4.696a1.5 1.5 0 0 1 2.121 0z"
  }))
});
ChartLineIcon.displayName = 'ChartLineIcon';
var _default = ChartLineIcon;
exports.default = _default;