"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var CheckmarkIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    d: "M1.282 9.682a1 1 0 1 1 1.415-1.414l4.242 4.242-1.414 1.415-4.243-4.243z"
  }), _react.default.createElement("path", {
    d: "M5.525 11.096l7.778-7.778a1 1 0 1 1 1.414 1.414L6.94 12.51l-1.414-1.414z"
  }))
});
CheckmarkIcon.displayName = 'CheckmarkIcon';
var _default = CheckmarkIcon;
exports.default = _default;