"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ChevronUpIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M11.146 9.146a.5.5 0 0 1-.353.854H5.207a.5.5 0 0 1-.353-.854l2.792-2.792a.5.5 0 0 1 .708 0l2.792 2.792z"
  }))
});
ChevronUpIcon.displayName = 'ChevronUpIcon';
var _default = ChevronUpIcon;
exports.default = _default;