"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ClockIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("g", {
    clipPath: "url(#clip0)"
  }, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-5.293 1.293L9 7.586V3.5a1 1 0 1 0-2 0v4.914l2.293 2.293a1 1 0 0 0 1.414-1.414z"
  })), _react.default.createElement("defs", null, _react.default.createElement("clipPath", {
    id: "clip0"
  }, _react.default.createElement("path", {
    d: "M0 0h16v16H0z"
  }))))
});
ClockIcon.displayName = 'ClockIcon';
var _default = ClockIcon;
exports.default = _default;