"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var CompareIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M7 3a1 1 0 1 1 2 0v10a1 1 0 1 1-2 0V3zm9 5a4 4 0 0 1-5 3.874V4.126A4 4 0 0 1 16 8zM5 12V4L.956 10.47A1 1 0 0 0 1.804 12H5z"
  }))
});
CompareIcon.displayName = 'CompareIcon';
var _default = CompareIcon;
exports.default = _default;