"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var EmojiIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm0-2A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"
  }), _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M12 8.015V8v-.015.03zM11.465 10h-6.93A3.998 3.998 0 0 0 8 12c1.48 0 2.773-.804 3.465-2z"
  }), _react.default.createElement("circle", {
    cx: "5",
    cy: "7",
    r: "1"
  }), _react.default.createElement("circle", {
    cx: "11",
    cy: "7",
    r: "1"
  }))
});
EmojiIcon.displayName = 'EmojiIcon';
var _default = EmojiIcon;
exports.default = _default;