"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var FolderIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M2.5 6l-.36-2.876A1 1 0 0 1 3.133 2h2.766c1.036 0 2.042.353 2.851 1 .81.647 1.815 1 2.85 1h1.12a1 1 0 0 1 .97 1.243L13.5 6h-11zM0 7l.781 6.248A2 2 0 0 0 2.766 15h10.468a2 2 0 0 0 1.985-1.752L16 7H0z"
  }))
});
FolderIcon.displayName = 'FolderIcon';
var _default = FolderIcon;
exports.default = _default;