"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var GearIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M2.568 8.59a1 1 0 0 0 0-1.18l-1.56-2.13a7.492 7.492 0 0 1 1.143-1.974l2.621.285A1 1 0 0 0 5.795 3L6.86.586a7.559 7.559 0 0 1 2.28 0L10.205 3a1 1 0 0 0 1.023.59l2.622-.284A7.49 7.49 0 0 1 14.99 5.28l-1.559 2.13a1 1 0 0 0 0 1.18l1.56 2.13a7.491 7.491 0 0 1-1.142 1.974l-2.622-.285a1 1 0 0 0-1.023.59L9.14 15.415a7.56 7.56 0 0 1-2.28 0L5.795 13a1 1 0 0 0-1.023-.59l-2.622.284A7.493 7.493 0 0 1 1.01 10.72l1.559-2.13zM8 10a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"
  }))
});
GearIcon.displayName = 'GearIcon';
var _default = GearIcon;
exports.default = _default;