"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var InstagramIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M8 0C5.827 0 5.555.01 4.702.048 3.85.087 3.269.222 2.76.42a3.921 3.921 0 0 0-1.417.923A3.922 3.922 0 0 0 .42 2.76C.222 3.269.087 3.85.048 4.702.01 5.556 0 5.828 0 8.001s.01 2.445.048 3.299c.039.851.174 1.433.372 1.942.204.526.478.972.923 1.417.444.445.89.718 1.417.923.509.198 1.09.333 1.942.372.853.039 1.125.048 3.298.048s2.445-.01 3.298-.048c.852-.04 1.433-.174 1.942-.372a3.922 3.922 0 0 0 1.417-.923c.445-.445.719-.891.923-1.417.198-.509.333-1.09.372-1.942C15.99 10.446 16 10.174 16 8s-.01-2.445-.048-3.299c-.039-.851-.174-1.433-.372-1.942a3.922 3.922 0 0 0-.923-1.417A3.921 3.921 0 0 0 13.24.42c-.509-.198-1.09-.333-1.942-.372C10.445.01 10.173 0 8 0zm0 1.442c2.136 0 2.39.008 3.233.046.78.036 1.203.166 1.485.276.374.145.64.318.92.598.28.28.453.547.598.92.11.282.24.706.276 1.486.038.844.047 1.097.047 3.233s-.009 2.39-.047 3.233c-.036.78-.166 1.204-.276 1.486-.145.373-.318.64-.598.92-.28.28-.546.453-.92.598-.282.11-.705.24-1.485.276-.844.038-1.097.046-3.233.046s-2.39-.008-3.233-.046c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.479 2.479 0 0 1-.598-.92c-.11-.282-.24-.706-.276-1.486-.038-.844-.047-1.097-.047-3.233s.009-2.39.047-3.233c.036-.78.166-1.204.276-1.486.145-.373.318-.64.598-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.844-.038 1.097-.046 3.233-.046z"
  }), _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M8 10.668a2.667 2.667 0 1 1 0-5.334 2.667 2.667 0 0 1 0 5.334zm0-6.776a4.108 4.108 0 1 0 0 8.217 4.108 4.108 0 0 0 0-8.217zM13.23 3.73a.96.96 0 1 1-1.92 0 .96.96 0 0 1 1.92 0z"
  }))
});
InstagramIcon.displayName = 'InstagramIcon';
var _default = InstagramIcon;
exports.default = _default;