"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ListIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    d: "M6 2h8a1 1 0 1 1 0 2H6V2zM1 3a1 1 0 0 1 1-1h2v2H2a1 1 0 0 1-1-1zM6 7h8a1 1 0 1 1 0 2H6V7zM1 8a1 1 0 0 1 1-1h2v2H2a1 1 0 0 1-1-1zM6 12h8a1 1 0 1 1 0 2H6v-2zM1 13a1 1 0 0 1 1-1h2v2H2a1 1 0 0 1-1-1z"
  }))
});
ListIcon.displayName = 'ListIcon';
var _default = ListIcon;
exports.default = _default;