"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var LoadIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12zm0 2A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
  }), _react.default.createElement("defs", null, _react.default.createElement("radialGradient", {
    id: "paint0_angular",
    cx: "0",
    cy: "0",
    r: "1",
    gradientUnits: "userSpaceOnUse",
    gradientTransform: "matrix(0 8 -8 0 8 8)"
  }, _react.default.createElement("stop", null), _react.default.createElement("stop", {
    offset: "0.602"
  }), _react.default.createElement("stop", {
    offset: "0.707",
    stopOpacity: "0.906"
  }), _react.default.createElement("stop", {
    offset: "0.801",
    stopColor: "#fff",
    stopOpacity: "0"
  }), _react.default.createElement("stop", {
    offset: "1",
    stopColor: "#fff",
    stopOpacity: "0"
  }))))
});
LoadIcon.displayName = 'LoadIcon';
var _default = LoadIcon;
exports.default = _default;