"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var LocationIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M10.06 13.392C12.236 10.713 14 8.542 14 6A6 6 0 0 0 2 6c0 2.541 1.764 4.713 3.94 7.392C6.6 14.206 7.3 15.067 8 16c.7-.933 1.399-1.794 2.06-2.608zM8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
  }))
});
LocationIcon.displayName = 'LocationIcon';
var _default = LocationIcon;
exports.default = _default;