"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var MessengerIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M8 0C3.582 0 0 3.316 0 7.407c0 2.332 1.163 4.41 2.981 5.769V16l2.724-1.495c.727.201 1.497.31 2.295.31 4.418 0 8-3.317 8-7.408C16 3.317 12.418 0 8 0zm.795 9.975L6.758 7.803 2.783 9.975l4.372-4.642 2.087 2.173 3.926-2.173-4.373 4.642z"
  }))
});
MessengerIcon.displayName = 'MessengerIcon';
var _default = MessengerIcon;
exports.default = _default;