"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var PencilIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    d: "M14.142.837a1 1 0 0 0-1.414 0l-.707.707 2.121 2.122.707-.708a1 1 0 0 0 0-1.414l-.707-.707zM11.314 2.251l2.121 2.122-8.485 8.485-2.381 1.19a.694.694 0 0 1-.931-.93l1.19-2.381 8.486-8.486z"
  }))
});
PencilIcon.displayName = 'PencilIcon';
var _default = PencilIcon;
exports.default = _default;