"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var PersonIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M7.96 8c1.634 0 2.96-1.343 2.96-3S9.593 2 7.96 2C6.325 2 5 3.343 5 5s1.325 3 2.96 3z"
  }), _react.default.createElement("path", {
    d: "M2.07 13.654A5.79 5.79 0 0 1 7.745 9h.508a5.789 5.789 0 0 1 5.677 4.654.29.29 0 0 1-.284.346H2.353a.29.29 0 0 1-.284-.346z"
  }))
});
PersonIcon.displayName = 'PersonIcon';
var _default = PersonIcon;
exports.default = _default;