"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var PlaceholderIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("rect", {
    width: "16",
    height: "16",
    rx: "4"
  }))
});
PlaceholderIcon.displayName = 'PlaceholderIcon';
var _default = PlaceholderIcon;
exports.default = _default;