"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var PlusIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3a1 1 0 0 0-1 1v8a1 1 0 1 0 2 0V9h3a1 1 0 1 0 0-2H9V4a1 1 0 0 0-1-1zM4 9h2V7H4a1 1 0 0 0 0 2z"
  }))
});
PlusIcon.displayName = 'PlusIcon';
var _default = PlusIcon;
exports.default = _default;