"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var RefreshIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    d: "M7 1a7 7 0 1 0 0 14h1a1 1 0 1 0 0-2H7a5 5 0 1 1 5-5h-1.793a.5.5 0 0 0-.353.854l2.793 2.793a.5.5 0 0 0 .707 0l2.793-2.793A.5.5 0 0 0 15.793 8H14a7 7 0 0 0-7-7z"
  }))
});
RefreshIcon.displayName = 'RefreshIcon';
var _default = RefreshIcon;
exports.default = _default;