"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var ReturnIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    d: "M8.002 4.003a1 1 0 0 1 1.656-.756l4.487 3.9a1 1 0 0 1-.013 1.521l-4.48 3.76a1 1 0 0 1-1.644-.764l-.006-7.661zM4 4.8a1 1 0 1 0-2 0v.382A3.618 3.618 0 0 0 5.618 8.8H8v-2H5.618A1.618 1.618 0 0 1 4 5.182V4.8z"
  }))
});
ReturnIcon.displayName = 'ReturnIcon';
var _default = ReturnIcon;
exports.default = _default;