"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var SearchIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M9.5 10a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zm0 2a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11z"
  }), _react.default.createElement("path", {
    d: "M5.95 9l1.414 1.414-4.243 4.243a1 1 0 0 1-1.414-1.414L5.95 9z"
  }))
});
SearchIcon.displayName = 'SearchIcon';
var _default = SearchIcon;
exports.default = _default;