"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var TagIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M14 1H8.414a1 1 0 0 0-.707.293l-7 7a1 1 0 0 0 0 1.414l5.586 5.586a1 1 0 0 0 1.414 0l7-7A1 1 0 0 0 15 7.586V2a1 1 0 0 0-1-1zm-2.5 5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"
  }))
});
TagIcon.displayName = 'TagIcon';
var _default = TagIcon;
exports.default = _default;