"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _react = _interopRequireDefault(require("react"));

var _createIconComponent = _interopRequireDefault(require("../utils/createIconComponent"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
var UnlockedIcon = (0, _createIconComponent.default)({
  content: _react.default.createElement("g", null, _react.default.createElement("path", {
    fillRule: "evenodd",
    clipRule: "evenodd",
    d: "M3 7a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H3zm5 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2zM5 6a3 3 0 0 1 5.332-1.888L12 3a5 5 0 0 0-9 3v1h2V6z"
  }))
});
UnlockedIcon.displayName = 'UnlockedIcon';
var _default = UnlockedIcon;
exports.default = _default;