export declare const blue = "#2c4bff";
export declare const blueDark = "#1F35B3";
export declare const blueDarker = "#121E66";
export declare const blueLight = "#6B81FF";
export declare const blueLighter = "#ABB7FF";
export declare const blueLightest = "#D5DBFF";
export declare const blueLightest50 = "rgba(213, 219, 255, 0.5)";
export declare const purple = "#9C2BFF";
export declare const purpleDark = "#6D1EB3";
export declare const purpleDarker = "#3E1166";
export declare const purpleLight = "#BA6BFF";
export declare const purpleLighter = "#D7AAFF";
export declare const purpleLightest = "#EBD5FF";
export declare const pink = "#D925AC";
export declare const pinkDark = "#981A78";
export declare const pinkDarker = "#570F45";
export declare const pinkLight = "#E466C5";
export declare const pinkLighter = "#F0A8DE";
export declare const pinkLightest = "#F7D3EE";
export declare const teal = "#00C8CF";
export declare const tealDark = "#008387";
export declare const tealDarker = "#005053";
export declare const tealLight = "#4DD9DD";
export declare const tealLighter = "#99E9EC";
export declare const tealLightest = "#CCF4F5";
export declare const red = "#E0364F";
export declare const redDark = "#9D2637";
export declare const redDarker = "#5A1620";
export declare const redLight = "#E97284";
export declare const redLighter = "#F3AFB9";
export declare const redLightest = "#F9D7DC";
export declare const orange = "#FF702C";
export declare const orangeDark = "#B34E1F";
export declare const orangeDarker = "#662D12";
export declare const orangeLight = "#FF9B6B";
export declare const orangeLighter = "#FFC6AB";
export declare const orangeLightest = "#FFE2D5";
export declare const yellow = "#FADE2A";
export declare const yellowDark = "#A8961D";
export declare const yellowDarker = "#645911";
export declare const yellowLight = "#FCE86A";
export declare const yellowLighter = "#FDF2AA";
export declare const yellowLightest = "#FEF8D4";
export declare const green = "#87C221";
export declare const greenDark = "#598016";
export declare const greenDarker = "#364E0D";
export declare const greenLight = "#ABD464";
export declare const greenLighter = "#CFE7A6";
export declare const greenLightest = "#E7F3D3";
export declare const white = "#FFFFFF";
export declare const grayLighter = "#F5F5F5";
export declare const grayLight = "#E0E0E0";
export declare const grayLight50 = "rgba(224, 224, 224, 0.5);";
export declare const gray = "#B8B8B8";
export declare const grayDark = "#636363";
export declare const grayDarker = "#3D3D3D";
export declare const grayDefault = "#77797a";
export declare const black = "#000000";
export declare const boxShadow = "#ABB7FF";
export declare const grayShadow = "0px 1px 4px rgba(0, 0, 0, 0.16)";
export declare const facebook = "#1877F2";
export declare const googlebusiness = "#478af5";
export declare const facebookDark = "#0C51AB";
export declare const googleplus = "#dd4b39";
export declare const instagram = "#F00276";
export declare const instagramDark = "#A51D5F";
export declare const linkedin = "#2867B2";
export declare const linkedinDark = "#1A4476";
export declare const pinterest = "#E60023";
export declare const pinterestDark = "#BD081C";
export declare const shopify = "#95BF47";
export declare const shopifyDark = "#5E8E3E";
export declare const twitter = "#1DA1F2";
export declare const tiktok = "#000000";
export declare const twitterDark = "#1174B0";
export declare const startpage = "#2c4bff";
export declare const canva = "#00c4cc";
export declare const canvaLight = "#00d9e1";
export declare const youtube = "#FF0000";
export declare const youtubeDark = "#C40000";
export declare const mastodon = "#6364FF";
export declare const transparent = "transparent";
declare const textColors: {
    red: string;
    white: string;
    gray: string;
    grayDark: string;
    grayDarker: string;
    blue: string;
};
export default textColors;
//# sourceMappingURL=colors.d.ts.map