export declare const fontFamily = "\"Roboto\", sans-serif";
export declare const fontSizeSmall = "12px";
export declare const fontSize = "14px";
export declare const fontWeightThin = 100;
export declare const fontWeightExtraLight = 200;
export declare const fontWeightLight = 300;
export declare const fontWeight = 400;
export declare const fontWeightMedium = 500;
export declare const fontWeightSemiBold = 600;
export declare const fontWeightBold = 700;
export declare const lineHeight = "16px";
export declare const lineHeightSmall = "14px";
//# sourceMappingURL=fonts.d.ts.map