export const blue = '#2c4bff'
export const blueDark = '#1F35B3'
export const blueDarker = '#121E66'
export const blueLight = '#6B81FF'
export const blueLighter = '#ABB7FF'
export const blueLightest = '#D5DBFF'
export const blueLightest50 = 'rgba(213, 219, 255, 0.5)'
export const purple = '#9C2BFF'
export const purpleDark = '#6D1EB3'
export const purpleDarker = '#3E1166'
export const purpleLight = '#BA6BFF'
export const purpleLighter = '#D7AAFF'
export const purpleLightest = '#EBD5FF'
export const pink = '#D925AC'
export const pinkDark = '#981A78'
export const pinkDarker = '#570F45'
export const pinkLight = '#E466C5'
export const pinkLighter = '#F0A8DE'
export const pinkLightest = '#F7D3EE'
export const teal = '#00C8CF'
export const tealDark = '#008387'
export const tealDarker = '#005053'
export const tealLight = '#4DD9DD'
export const tealLighter = '#99E9EC'
export const tealLightest = '#CCF4F5'
export const red = '#E0364F'
export const redDark = '#9D2637'
export const redDarker = '#5A1620'
export const redLight = '#E97284'
export const redLighter = '#F3AFB9'
export const redLightest = '#F9D7DC'
export const orange = '#FF702C'
export const orangeDark = '#B34E1F'
export const orangeDarker = '#662D12'
export const orangeLight = '#FF9B6B'
export const orangeLighter = '#FFC6AB'
export const orangeLightest = '#FFE2D5'
export const yellow = '#FADE2A'
export const yellowDark = '#A8961D'
export const yellowDarker = '#645911'
export const yellowLight = '#FCE86A'
export const yellowLighter = '#FDF2AA'
export const yellowLightest = '#FEF8D4'
export const green = '#87C221'
export const greenDark = '#598016'
export const greenDarker = '#364E0D'
export const greenLight = '#ABD464'
export const greenLighter = '#CFE7A6'
export const greenLightest = '#E7F3D3'

export const white = '#FFFFFF'
export const grayLighter = '#F5F5F5'
export const grayLight = '#E0E0E0'
export const grayLight50 = 'rgba(224, 224, 224, 0.5);'
export const gray = '#B8B8B8'
export const grayDark = '#636363'
export const grayDarker = '#3D3D3D'
export const grayDefault = '#77797a'
export const black = '#000000'

export const boxShadow = '#ABB7FF'
export const grayShadow = '0px 1px 4px rgba(0, 0, 0, 0.16)'

export const facebook = '#1877F2'
export const googlebusiness = '#478af5'
export const facebookDark = '#0C51AB'
export const googleplus = '#dd4b39'
export const instagram = '#F00276'
export const instagramDark = '#A51D5F'
export const linkedin = '#2867B2'
export const linkedinDark = '#1A4476'
export const pinterest = '#E60023'
export const pinterestDark = '#BD081C'
export const shopify = '#95BF47'
export const shopifyDark = '#5E8E3E'
export const twitter = '#1DA1F2'
export const tiktok = '#000000'
export const twitterDark = '#1174B0'
export const startpage = '#2c4bff'
export const canva = '#00c4cc'
export const canvaLight = '#00d9e1'
export const youtube = '#FF0000'
export const youtubeDark = '#C40000'
export const mastodon = '#6364FF'

export const transparent = 'transparent'

const textColors = {
  red,
  white,
  gray,
  grayDark,
  grayDarker,
  blue,
}

export default textColors
