/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const AddIcon = createIconComponent({
  content: (
    <g>
      <path d="M13 9a1 1 0 100-2H9V3a1 1 0 00-2 0v4H3a1 1 0 100 2h4v4a1 1 0 102 0V9h4z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
AddIcon.displayName = 'AddIcon'

export default AddIcon
