
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AddIcon = createIconComponent({
  content: (
    <g>
      <path d="M13 9a1 1 0 1 0 0-2H9V3a1 1 0 0 0-2 0v4H3a1 1 0 1 0 0 2h4v4a1 1 0 1 0 2 0V9h4z" />
    </g>
  ),
});
AddIcon.displayName = 'AddIcon';

export default AddIcon;
