/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AddMediaIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M15.59 4.28a2.86 2.86 0 11-5.719 0 2.86 2.86 0 015.719 0zm-3.206 3.6l-.034-.003a3.591 3.591 0 01-.96-.233v3.75c-1.113-.194-1.942-1.123-2.673-1.943-.63-.707-1.188-1.331-1.79-1.331-.752 0-1.636.961-2.446 1.842-.686.745-1.318 1.433-1.773 1.433-.482 0-.715-.284-.974-.6-.194-.237-.402-.492-.74-.66V5.604h8.36a3.56 3.56 0 01-.234-.991L.43 4.612a.43.43 0 00-.43.43v8.153c0 .237.194.43.43.43h11.525a.43.43 0 00.429-.43V7.88zm-9.48-1.063a1.142 1.142 0 11.001 2.284 1.142 1.142 0 010-2.284zm11.317-2.52a.25.25 0 01-.25.25h-1v1a.25.25 0 11-.5 0v-1h-1a.25.25 0 110-.5h1v-1a.25.25 0 11.5 0v1h1a.25.25 0 01.25.25z"
        clipRule="evenodd"
      />
    </g>
  ),
});
AddMediaIcon.displayName = 'AddMediaIcon';

export default AddMediaIcon;
