
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AnalyzeIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M7.134 1.927c-3.85 0-6.967 3.16-6.967 7.065 0 3.905 3.116 7.064 6.967 7.064 3.85 0 6.966-3.16 6.966-7.064H7.134V1.927z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M16 7.065C16 3.16 12.884 0 9.034 0v7.065H16z" />
    </g>
  ),
});
AnalyzeIcon.displayName = 'AnalyzeIcon';

export default AnalyzeIcon;
