
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AnalyzeIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M12.882 2.632a5.894 5.894 0 0 1 1.732 4.181H8.7V.9c1.514 0 3.027.578 4.182 1.732zm-5.969.043v5.91h5.913a5.914 5.914 0 1 1-5.913-5.91z" />
    </g>
  ),
});
AnalyzeIcon.displayName = 'AnalyzeIcon';

export default AnalyzeIcon;
