
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AnalyzeIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M8.794 2C11.67 2 14 4.362 14 7.28H8.794V2zM2.167 8.72c0-2.918 2.329-5.28 5.207-5.28v5.28h5.206c0 2.918-2.329 5.28-5.206 5.28-2.878 0-5.207-2.362-5.207-5.28z" />
    </g>
  ),
});
AnalyzeIcon.displayName = 'AnalyzeIcon';

export default AnalyzeIcon;
