/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AppearanceIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M9.714 1.838c1.295.646 2.48 1.584 3.161 2.235 1.029.924 1.184 1.445 1.505 2.522.083.28.177.597.301.969.209.625.547 3.063.096 3.51-.688.68-2.163-.15-1.807-.894 0 0 1.042-2.291.357-2.616l-2.71 5.447c-.14.276-.532.773-.903.894-1.059.346-3.168-.285-5.27-1.333-1.97-.983-3.041-2.064-3.35-2.989-.142-.428-.121-.822.049-1.158l3.526-6.914c.058-.114.208-.222.445-.3.747-.244 2.337-.502 4.6.627zm-4.6 2.117l-1.27 2.352L2.49 8.99s.044.948 2.624 2.234c2.553 1.274 3.98 1.345 4.086 1.215l2.727-5.35c-1.664.229-6.015-1.68-6.813-3.133zm3.36.768l.023.011c.79-.262 1.878-.37 3.062-.082-.714-.527-1.676-1.082-2.331-1.409-1.197-.597-3.204-1.345-3.478-.807-.271.532 1.742 1.798 2.725 2.287z"
        clipRule="evenodd"
      />
    </g>
  ),
});
AppearanceIcon.displayName = 'AppearanceIcon';

export default AppearanceIcon;
