
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ArrowRightIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M7 4.197a1 1 0 0 1 1.657-.755l4.483 3.904a1 1 0 0 1-.014 1.521l-4.484 3.757A1 1 0 0 1 7 11.857V9H3a1 1 0 1 1 0-2h4V4.197z" />
    </g>
  ),
});
ArrowRightIcon.displayName = 'ArrowRightIcon';

export default ArrowRightIcon;
