/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const ArrowLeftIcon = createIconComponent({
  content: (
    <g>
      <path d="M9 4.174a1 1 0 00-1.65-.759L2.885 7.241a1 1 0 000 1.518l4.463 3.826A1 1 0 009 11.825V9h4a1 1 0 100-2H9V4.174z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
ArrowLeftIcon.displayName = 'ArrowLeftIcon'

export default ArrowLeftIcon
