
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ArrowDownIcon = createIconComponent({
  content: (
    <g>
      <path d="M11.826 7a1 1 0 0 1 .76 1.65l-3.827 4.464a1 1 0 0 1-1.518 0L3.415 8.651A1 1 0 0 1 4.175 7h7.65z" />
      <path d="M7 7h2V3a1 1 0 1 0-2 0v4z" />
    </g>
  ),
});
ArrowDownIcon.displayName = 'ArrowDownIcon';

export default ArrowDownIcon;
