/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const ArrowUpIcon = createIconComponent({
  content: (
    <g>
      <path d="M4.174 9a1 1 0 01-.759-1.65l3.826-4.464a1 1 0 011.518 0l3.826 4.463A1 1 0 0111.825 9h-7.65z" />
      <path d="M9 9H7v4a1 1 0 102 0V9z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
ArrowUpIcon.displayName = 'ArrowUpIcon'

export default ArrowUpIcon
