
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ArrowLeftIcon = createIconComponent({
  content: (
    <g>
      <path d="M9 4.174a1 1 0 0 0-1.65-.759L2.885 7.241a1 1 0 0 0 0 1.518l4.463 3.826A1 1 0 0 0 9 11.825V9h4a1 1 0 1 0 0-2H9V4.174z" />
    </g>
  ),
});
ArrowLeftIcon.displayName = 'ArrowLeftIcon';

export default ArrowLeftIcon;
