
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ArrowDownIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M7 3v4H4.174a1 1 0 0 0-.759 1.65l3.826 4.464a1 1 0 0 0 1.518 0l3.826-4.463A1 1 0 0 0 11.825 7H9V3a1 1 0 1 0-2 0z" />
    </g>
  ),
});
ArrowDownIcon.displayName = 'ArrowDownIcon';

export default ArrowDownIcon;
