
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AssignedIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M4.083 4h7.834c.515 0 .864.524.666 1H3.417a.722.722 0 0 1 .666-1zM2.141 7.124l.75 6a1 1 0 0 0 .992.876h8.234a1 1 0 0 0 .993-.876l.75-6A1 1 0 0 0 12.867 6H3.133a1 1 0 0 0-.992 1.124z" />
      <path d="M8 2H6.03a.805.805 0 0 0-.78 1h5.5a.805.805 0 0 0-.78-1H8z" />
    </g>
  ),
});
AssignedIcon.displayName = 'AssignedIcon';

export default AssignedIcon;
