
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const AttachIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M7 1.75c-.69 0-1.25.56-1.25 1.25v9a2.25 2.25 0 0 0 4.5 0V6a.75.75 0 0 1 1.5 0v6a3.75 3.75 0 1 1-7.5 0V3a2.75 2.75 0 0 1 5.5 0v8a1.75 1.75 0 1 1-3.5 0V6a.75.75 0 0 1 1.5 0v5a.25.25 0 1 0 .5 0V3c0-.69-.56-1.25-1.25-1.25z" />
    </g>
  ),
});
AttachIcon.displayName = 'AttachIcon';

export default AttachIcon;
