/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const BandcampIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_2376_1716)">
        <path
          fillRule="evenodd"
          d="M8 16A8 8 0 108 0a8 8 0 000 16zm6-11.5H5.5l-3.5 7h8.5l3.5-7z"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="clip0_2376_1716">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
})
BandcampIcon.displayName = 'BandcampIcon'

export default BandcampIcon
