/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const BandcampIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 16A8 8 0 108 0a8 8 0 000 16zm6-11.5H5.5l-3.5 7h8.5l3.5-7z"
        clipRule="evenodd"
      />
    </g>
  ),
});
BandcampIcon.displayName = 'BandcampIcon';

export default BandcampIcon;
