/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const BookmarkOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M6.938 8.902A1.5 1.5 0 019.053 8.9l3.447 3.421V2.5h-9v9.82l3.438-3.418zm1.058 1.064l4.88 4.843a.642.642 0 00.721.134A.701.701 0 0014 14.3V1.7c0-.387-.298-.7-.666-.7H2.666C2.298 1 2 1.313 2 1.7v12.6c0 .28.158.532.403.643.244.11.528.058.721-.134l4.872-4.843z"
        clipRule="evenodd"
      />
    </g>
  ),
});
BookmarkOutlineIcon.displayName = 'BookmarkOutlineIcon';

export default BookmarkOutlineIcon;
