/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const BookmarkOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M6.916 8.902A1.554 1.554 0 019.074 8.9l3.52 3.421V2.5H3.406v9.82l3.51-3.418zm1.08 1.064l4.982 4.843a.666.666 0 00.736.134.7.7 0 00.411-.643V1.7a.69.69 0 00-.68-.7H2.555a.69.69 0 00-.68.7v12.6a.7.7 0 00.411.643c.25.11.54.058.737-.134l4.973-4.843z"
        clipRule="evenodd"
      />
    </g>
  ),
})
BookmarkOutlineIcon.displayName = 'BookmarkOutlineIcon'

export default BookmarkOutlineIcon
