/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const BookmarkFilledIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M1.875 1.7c0-.387.304-.7.68-.7h10.89a.69.69 0 01.68.7v12.6a.7.7 0 01-.411.643.666.666 0 01-.736-.134L7.996 9.966l-4.973 4.843a.666.666 0 01-.737.134.7.7 0 01-.411-.643V1.7z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
BookmarkFilledIcon.displayName = 'BookmarkFilledIcon'

export default BookmarkFilledIcon
