/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const BookmarkFilledIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2 1.7c0-.387.298-.7.666-.7h10.668c.368 0 .666.313.666.7v12.6c0 .28-.158.532-.403.643a.642.642 0 01-.72-.134L7.995 9.966l-4.872 4.843a.642.642 0 01-.721.134A.701.701 0 012 14.3V1.7z"
        clipRule="evenodd"
      />
    </g>
  ),
});
BookmarkFilledIcon.displayName = 'BookmarkFilledIcon';

export default BookmarkFilledIcon;
