/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const BookmarkOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M6.762 9.03a1.776 1.776 0 012.466 0l4.022 3.91V1.714H2.75v11.223L6.762 9.03zm1.233 1.216l5.694 5.536a.76.76 0 00.841.153.8.8 0 00.47-.735V.8c0-.442-.348-.8-.777-.8H1.777A.789.789 0 001 .8v14.4a.8.8 0 00.47.735.761.761 0 00.842-.154l5.683-5.535z"
        clipRule="evenodd"
      />
    </g>
  ),
});
BookmarkOutlineIcon.displayName = 'BookmarkOutlineIcon';

export default BookmarkOutlineIcon;
