
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const BufferIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M2 4.194L8 .968l6 3.226-6 3.174-6-3.174zM3.929 7L8 9.069 12.114 7l1.918.965L8 11 2.032 7.965 3.93 7zm-.033 3.6L8 12.881l4.082-2.281L14 11.66 8 15l-6-3.34 1.896-1.06z" />
    </g>
  ),
});
BufferIcon.displayName = 'BufferIcon';

export default BufferIcon;
