/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const BuildingIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M5.85.5a.5.5 0 01.5-.5h8a.5.5 0 01.5.5V16H12v-3.75a.25.25 0 00-.25-.25h-2.5a.25.25 0 00-.25.25V16H1V5.5a.5.5 0 01.5-.5h4.35V.5zM9.25 4a.25.25 0 00-.25.25v2.5c0 .138.112.25.25.25h2.5a.25.25 0 00.25-.25v-2.5a.25.25 0 00-.25-.25h-2.5zM9 8.25A.25.25 0 019.25 8h2.5a.25.25 0 01.25.25v2.5a.25.25 0 01-.25.25h-2.5a.25.25 0 01-.25-.25v-2.5z"
        clipRule="evenodd"
      />
    </g>
  ),
});
BuildingIcon.displayName = 'BuildingIcon';

export default BuildingIcon;
