/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ButtonLinkIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2 5C.895 5 0 5.672 0 6.5v3c0 .828.895 1.5 2 1.5h12c1.105 0 2-.672 2-1.5v-3c0-.828-.895-1.5-2-1.5H2zm1 2.25c-.552 0-1 .336-1 .75s.448.75 1 .75h10c.552 0 1-.336 1-.75s-.448-.75-1-.75H3z"
        clipRule="evenodd"
      />
    </g>
  ),
});
ButtonLinkIcon.displayName = 'ButtonLinkIcon';

export default ButtonLinkIcon;
