/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const CalendarAddIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3 0a1 1 0 011 1v1h6V1a1 1 0 112 0v1a5 5 0 00-5 5H2v6h10v-1c.711 0 1.387-.148 2-.416V14a1 1 0 01-1 1H1a1 1 0 01-1-1V3a1 1 0 011-1h1V1a1 1 0 011-1zm13 7a4 4 0 11-8 0 4 4 0 018 0zm-2 .444a.444.444 0 100-.888h-1.556V5a.444.444 0 10-.889 0v1.556H10a.444.444 0 000 .888h1.556V9a.444.444 0 00.889 0V7.444H14z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
CalendarAddIcon.displayName = 'CalendarAddIcon'

export default CalendarAddIcon
