
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CameraIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM4 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      <path d="M4 5a4 4 0 1 1 8 0H4z" />
    </g>
  ),
});
CameraIcon.displayName = 'CameraIcon';

export default CameraIcon;
