/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const CameraIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M0 4a1 1 0 011-1h14a1 1 0 011 1v10a1 1 0 01-1 1H1a1 1 0 01-1-1V4zm8 8a3 3 0 100-6 3 3 0 000 6zM4 6a1 1 0 11-2 0 1 1 0 012 0z"
        clipRule="evenodd"
      />
      <path d="M12 5H4a4 4 0 118 0z" />
    </g>
  ),
})
CameraIcon.displayName = 'CameraIcon'

export default CameraIcon
