/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CaptionIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2.5 3.5v9h11v-9h-11zM1 3.036C1 2.464 1.448 2 2 2h12c.552 0 1 .464 1 1.036v9.928c0 .572-.448 1.036-1 1.036H2c-.552 0-1-.464-1-1.036V3.036zm3 4.92c0-.43.336-.777.75-.777h3.5c.414 0 .75.347.75.776a.764.764 0 01-.75.777h-3.5A.764.764 0 014 7.955zm3.75 1.812a.764.764 0 00-.75.777c0 .429.336.776.75.776h3.5c.414 0 .75-.347.75-.776a.764.764 0 00-.75-.777h-3.5zM10 7.955c0-.429.336-.776.75-.776h.5c.414 0 .75.347.75.776a.764.764 0 01-.75.777h-.5a.764.764 0 01-.75-.777zM4.75 9.768a.764.764 0 00-.75.777c0 .429.336.776.75.776h.5c.414 0 .75-.347.75-.776a.764.764 0 00-.75-.777h-.5z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CaptionIcon.displayName = 'CaptionIcon';

export default CaptionIcon;
