/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CardIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2 3.75a1 1 0 00-1 1v6.39a1 1 0 001 1h12a1 1 0 001-1V4.75a1 1 0 00-1-1H2zM3.25 6a.5.5 0 01.5-.5h2a.5.5 0 01.5.5v1.5a.5.5 0 01-.5.5h-2a.5.5 0 01-.5-.5V6zm0 3.5a.5.5 0 01.5-.5h8.5a.5.5 0 01.5.5v.088a.5.5 0 01-.5.5h-8.5a.5.5 0 01-.5-.5V9.5z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CardIcon.displayName = 'CardIcon';

export default CardIcon;
