/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const CaretRightIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M10.957 8.957a1 1 0 000-1.414l-5.25-5.25a1 1 0 00-1.414 1.414L8.836 8.25l-4.543 4.543a1 1 0 101.414 1.414l5.25-5.25z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
CaretRightIcon.displayName = 'CaretRightIcon'

export default CaretRightIcon
