/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CaretDownIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M7.336 4.293a1 1 0 011.414 0L14 9.543a1 1 0 01-1.414 1.414L8.043 6.414 3.5 10.957a1 1 0 01-1.414-1.414l5.25-5.25z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CaretDownIcon.displayName = 'CaretDownIcon';

export default CaretDownIcon;
