/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CarouselIcon = createIconComponent({
  content: (
    <g>
      <path d="M2.5.5a2 2 0 00-2 2v7.52a2 2 0 002 2h8.52a1 1 0 001-1V2.5a2 2 0 00-2-2H2.5z" />
      <path d="M5.735 15.254A2 2 0 013.77 13.62h8.85a1 1 0 001-1V3.767a2 2 0 011.636 1.967v7.52a2 2 0 01-2 2h-7.52z" />
    </g>
  ),
});
CarouselIcon.displayName = 'CarouselIcon';

export default CarouselIcon;
