/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ChannelsIcon = createIconComponent({
  content: (
    <g>
      <path d="M2 1a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V2a1 1 0 00-1-1H2zm0 8a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1v-4a1 1 0 00-1-1H2zm7-7a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1V2zm1 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1v-4a1 1 0 00-1-1h-4z" />
    </g>
  )
});
ChannelsIcon.displayName = 'ChannelsIcon';

export default ChannelsIcon;
