/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ChartLineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M15.38 2.744a1.5 1.5 0 010 2.121l-6.818 6.818L5.5 8.62l-2.94 2.94A1.5 1.5 0 11.44 9.439L5.5 4.38l3.062 3.06 4.696-4.696a1.5 1.5 0 012.121 0z"
        clipRule="evenodd"
      />
    </g>
  )
});
ChartLineIcon.displayName = 'ChartLineIcon';

export default ChartLineIcon;
