
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CheckmarkIcon = createIconComponent({
  content: (
    <g>
      <path d="M1.282 9.682a1 1 0 1 1 1.415-1.414l4.242 4.242-1.414 1.415-4.243-4.243z" />
      <path d="M5.525 11.096l7.778-7.778a1 1 0 1 1 1.414 1.414L6.94 12.51l-1.414-1.414z" />
    </g>
  ),
});
CheckmarkIcon.displayName = 'CheckmarkIcon';

export default CheckmarkIcon;
