
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CheckmarkIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M3.06 8.146a1 1 0 0 0 0 1.415l2.83 2.828 1.413-1.414 5.657-5.657a1 1 0 1 0-1.414-1.414L5.889 9.56 4.475 8.146a1 1 0 0 0-1.414 0z" />
    </g>
  ),
});
CheckmarkIcon.displayName = 'CheckmarkIcon';

export default CheckmarkIcon;
