
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ChevronUpIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M11.146 9.146a.5.5 0 0 1-.353.854H5.207a.5.5 0 0 1-.353-.854l2.792-2.792a.5.5 0 0 1 .708 0l2.793 2.792z" />
    </g>
  ),
});
ChevronUpIcon.displayName = 'ChevronUpIcon';

export default ChevronUpIcon;
