/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ChevronUpIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M11.146 9.146a.5.5 0 01-.353.854H5.207a.5.5 0 01-.353-.854l2.792-2.792a.5.5 0 01.708 0l2.793 2.792z"
        clipRule="evenodd"
      />
    </g>
  ),
});
ChevronUpIcon.displayName = 'ChevronUpIcon';

export default ChevronUpIcon;
