
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ClockIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0)">
        <path fillRule="evenodd" clipRule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-5.293 1.293L9 7.586V3.5a1 1 0 1 0-2 0v4.914l2.293 2.293a1 1 0 0 0 1.414-1.414z" />
      </g>
      <defs>
        <clipPath id="clip0">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>

    </g>
  ),
});
ClockIcon.displayName = 'ClockIcon';

export default ClockIcon;
