
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ClockIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M14 8A6 6 0 1 1 2 8a6 6 0 0 1 12 0zm2 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 3a.5.5 0 0 0-1 0v5.207l.146.147 2 2a.5.5 0 0 0 .708-.708L8.5 7.793V3z" />
    </g>
  ),
});
ClockIcon.displayName = 'ClockIcon';

export default ClockIcon;
