/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const CommentRoundFilledIcon = createIconComponent({
  content: (
    <g>
      <path d="M11.477 12.992a6.5 6.5 0 112.015-2.015L14.5 14l-3.023-1.008z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
CommentRoundFilledIcon.displayName = 'CommentRoundFilledIcon'

export default CommentRoundFilledIcon
