/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CommentRoundOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M11.9 11.414l-.957-.179-.407.283a4.75 4.75 0 111.482-1.482l-.281.405.162.973zM8 14.25a6.72 6.72 0 003.51-.983l1.962.654a.75.75 0 00.949-.949l-.654-1.962A6.75 6.75 0 108 14.25z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CommentRoundOutlineIcon.displayName = 'CommentRoundOutlineIcon';

export default CommentRoundOutlineIcon;
