/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CommentRoundOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M11 11.5l1.205.226L12 10.5l.226-.326a5 5 0 10-1.552 1.552L11 11.5zm3.184 1.551a.5.5 0 01-.633.633l-2.074-.691a6.5 6.5 0 112.015-2.015l.692 2.073z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CommentRoundOutlineIcon.displayName = 'CommentRoundOutlineIcon';

export default CommentRoundOutlineIcon;
