/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CopyIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2 6v8h8V6H2zM1 4a1 1 0 00-1 1v10a1 1 0 001 1h10a1 1 0 001-1V5a1 1 0 00-1-1H1zm11-3a1 1 0 011-1h1a2 2 0 012 2v1a1 1 0 11-2 0V2h-1a1 1 0 01-1-1zm3 4a1 1 0 011 1v1a1 1 0 11-2 0V6a1 1 0 011-1zm0 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM8 1a1 1 0 011-1h1a1 1 0 110 2H9a1 1 0 01-1-1zM4 1a1 1 0 011-1h1a1 1 0 010 2H5a1 1 0 01-1-1z"
        clipRule="evenodd"
      ></path>
    </g>
  ),
});
CopyIcon.displayName = 'CopyIcon';

export default CopyIcon;
