
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CrossIcon = createIconComponent({
  content: (
    <g>
      <path d="M10.828 12.243a1 1 0 0 0 1.415-1.415L9.414 8l2.829-2.828a1 1 0 0 0-1.415-1.415L8 6.586 5.172 3.757a1 1 0 0 0-1.415 1.415L6.586 8l-2.829 2.828a1 1 0 0 0 1.415 1.415L8 9.414l2.828 2.829z" />
    </g>
  ),
});
CrossIcon.displayName = 'CrossIcon';

export default CrossIcon;
