
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const CrossIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0)">
        <path fillRule="evenodd" clipRule="evenodd" d="M10.828 12.243a1 1 0 1 0 1.415-1.415L9.414 8l2.829-2.828a1 1 0 1 0-1.415-1.415L8 6.586 5.172 3.757a1 1 0 0 0-1.415 1.415L6.586 8l-2.829 2.828a1 1 0 1 0 1.415 1.415L8 9.414l2.828 2.829z" />
      </g>
      <defs>
        <clipPath id="clip0">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>

    </g>
  ),
});
CrossIcon.displayName = 'CrossIcon';

export default CrossIcon;
