/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const DayIcon = createIconComponent({
  content: (
    <g>
      <path d="M2.98 1c-.43 0-.78.448-.78 1v2c0 .552.35 1 .78 1 .43 0 .78-.448.78-1V2c0-.552-.35-1-.78-1z" />
      <path
        fillRule="evenodd"
        d="M1 4.16v9.661a1 1 0 001 1h11.9a1 1 0 001-1v-8.94a1.98 1.98 0 01-3.825-.72V2.41h-1.09v1.75a1.98 1.98 0 11-3.96 0V2.41H4.96v1.75a1.98 1.98 0 11-3.96 0zm6.092 7.915L5.277 10.26a.792.792 0 011.12-1.12l.695.696L9.57 7.358a.792.792 0 011.12 1.12l-3.598 3.597z"
        clipRule="evenodd"
      />
      <path d="M7.23 2c0-.552.35-1 .78-1 .43 0 .78.448.78 1v2c0 .552-.35 1-.78 1-.43 0-.78-.448-.78-1V2zm5.815-1c-.43 0-.78.448-.78 1v2c0 .552.35 1 .78 1 .43 0 .78-.448.78-1V2c0-.552-.35-1-.78-1z" />
    </g>
  )
});
DayIcon.displayName = 'DayIcon';

export default DayIcon;
