/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const DraftsIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M11.544 6.33l-4.552 4.553-2.105 1.052a.613.613 0 01-.822-.822l1.052-2.105 4.61-4.61-.002-.001 1.414-1.415.002.002 1.475-1.475 1.875 1.875-1.527 1.527.004.004-1.42 1.42-.004-.004zM9.318 1.06l.789.833-1.415 1.415-.825-.871C7.569 2.123 7.235 2 6.944 2H2v12h10V8.008l1.748-1.748c.165.47.252.975.252 1.491V14c0 1.105-.784 2-1.75 2H1.75C.784 16 0 15.105 0 14V2C0 .895.784 0 1.75 0h5.194c.88 0 1.728.379 2.374 1.06zm5.798 1.699L13.241.884l.626-.625a.884.884 0 011.25 0l.624.625a.884.884 0 01.004 1.246l-.004.004-.625.625z"
        clipRule="evenodd"
      />
    </g>
  ),
});
DraftsIcon.displayName = 'DraftsIcon';

export default DraftsIcon;
