/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const DragIndicatorIcon = createIconComponent({
  content: (
    <g>
      <path d="M7.089 2.444a1.444 1.444 0 11-2.889 0 1.444 1.444 0 012.889 0zm5.556 0a1.444 1.444 0 11-2.89 0 1.444 1.444 0 012.89 0zM7.089 8A1.444 1.444 0 114.2 8a1.444 1.444 0 012.889 0zm5.556 0a1.444 1.444 0 11-2.89 0 1.444 1.444 0 012.89 0zm-5.556 5.556a1.444 1.444 0 11-2.889 0 1.444 1.444 0 012.889 0zm5.556 0a1.444 1.444 0 11-2.89 0 1.444 1.444 0 012.89 0z" />
    </g>
  ),
})
DragIndicatorIcon.displayName = 'DragIndicatorIcon'

export default DragIndicatorIcon
