/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const DropboxIcon = createIconComponent({
  content: (
    <g>
      <path d="M8.01 4.58L4.006 7.158l4.006 2.58-4.006 2.579L0 9.717l4.005-2.58L0 4.58 4.005 2l4.006 2.58zm-4.026 8.555l4.005-2.58 4.006 2.58-4.006 2.58-4.005-2.58zm4.027-3.418l4.005-2.58L8.011 4.58 11.995 2 16 4.58l-4.005 2.579L16 9.739l-4.005 2.579L8.01 9.717z"></path>
    </g>
  ),
});
DropboxIcon.displayName = 'DropboxIcon';

export default DropboxIcon;
