
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const EmojiIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm0-2A6 6 0 1 0 8 2a6 6 0 0 0 0 12z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M12 8.015V8v-.015.03zM11.465 10h-6.93A3.998 3.998 0 0 0 8 12c1.48 0 2.773-.804 3.465-2z" />
      <circle cx="5" cy="7" r="1" />
      <circle cx="11" cy="7" r="1" />
    </g>
  ),
});
EmojiIcon.displayName = 'EmojiIcon';

export default EmojiIcon;
