/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from "react";
import createIconComponent from "../utils/createIconComponent";

const EmojiIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 16A8 8 0 108 0a8 8 0 000 16zm0-2A6 6 0 108 2a6 6 0 000 12z"
        clipRule="evenodd"
      />
      <path d="M12 8.015v-.03.03zM11.465 10h-6.93A3.998 3.998 0 008 12c1.48 0 2.773-.804 3.465-2zM6 7a1 1 0 11-2 0 1 1 0 012 0zm6 0a1 1 0 11-2 0 1 1 0 012 0z" />
    </g>
  ),
});
EmojiIcon.displayName = "EmojiIcon";

export default EmojiIcon;
