
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const FacebookIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M14.227 1H1.773A.773.773 0 0 0 1 1.773v12.454c0 .427.346.773.773.773h6.705V9.578H6.653V7.466h1.825V5.907c0-1.808 1.104-2.793 2.717-2.793.773 0 1.437.058 1.63.084v1.89h-1.118c-.877 0-1.047.417-1.047 1.029v1.349h2.092l-.272 2.112h-1.82V15h3.567a.773.773 0 0 0 .773-.773V1.773A.773.773 0 0 0 14.227 1z" />
    </g>
  ),
});
FacebookIcon.displayName = 'FacebookIcon';

export default FacebookIcon;
