/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const FeedIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2.3 1A1.3 1.3 0 001 2.3v11.4A1.3 1.3 0 002.3 15h11.4a1.3 1.3 0 001.3-1.3V2.3A1.3 1.3 0 0013.7 1H2.3zm1.925 6.125a.6.6 0 00-.6.6v.55a.6.6 0 00.6.6h7.55a.6.6 0 00.6-.6v-.55a.6.6 0 00-.6-.6h-7.55zm-.6 4.1a.6.6 0 01.6-.6h7.55a.6.6 0 01.6.6v.55a.6.6 0 01-.6.6h-7.55a.6.6 0 01-.6-.6v-.55zm.6-7.6a.6.6 0 00-.6.6v.55a.6.6 0 00.6.6h7.55a.6.6 0 00.6-.6v-.55a.6.6 0 00-.6-.6h-7.55z"
        clipRule="evenodd"
      />
    </g>
  ),
})
FeedIcon.displayName = 'FeedIcon'

export default FeedIcon
