/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const FlagIcon = createIconComponent({
  content: (
    <g>
      <path d="M4 2a1 1 0 00-2 0v12a1 1 0 102 0V2zm1 8V2h9l-1.72 3.566a1 1 0 000 .868L14 10H5z" />
    </g>
  ),
});
FlagIcon.displayName = 'FlagIcon';

export default FlagIcon;
