/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const FlashIcon = createIconComponent({
  content: (
    <g>
      <path d="M14.037 6.612a.584.584 0 00-.537-.361H9.563l1.01-4.539a.584.584 0 00-1.016-.507L3.141 8.788a.583.583 0 00.443.962h3.273l-1.494 4.48a.583.583 0 00.263.682.584.584 0 00.533.045.582.582 0 00.19-.126l7.583-7.583a.583.583 0 00.105-.636z"></path>
    </g>
  ),
});
FlashIcon.displayName = 'FlashIcon';

export default FlashIcon;
