
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const FolderIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M2.5 6l-.36-2.876A1 1 0 0 1 3.133 2h2.766c1.036 0 2.042.353 2.851 1 .81.647 1.815 1 2.85 1h1.12a1 1 0 0 1 .97 1.243L13.5 6h-11zM0 7l.781 6.248A2 2 0 0 0 2.766 15h10.468a2 2 0 0 0 1.985-1.752L16 7H0z" />
    </g>
  ),
});
FolderIcon.displayName = 'FolderIcon';

export default FolderIcon;
