/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const FrequencyIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 16A8 8 0 108 0a8 8 0 000 16zm.762-11.467a1.029 1.029 0 00-2.057 0V8.29a1.03 1.03 0 00.3.77l2.562 2.56a1.029 1.029 0 001.454-1.454l-2.259-2.26V4.533z"
        clipRule="evenodd"
      />
    </g>
  ),
})
FrequencyIcon.displayName = 'FrequencyIcon'

export default FrequencyIcon
