/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const FrequencyIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 15A7 7 0 108 1a7 7 0 000 14zm.667-10.033a.9.9 0 00-1.8 0v3.286a.898.898 0 00.263.673l2.24 2.241a.9.9 0 001.274-1.272L8.667 7.918V4.967z"
        clipRule="evenodd"
      />
    </g>
  )
});
FrequencyIcon.displayName = 'FrequencyIcon';

export default FrequencyIcon;
