
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const GearIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M2.568 7.41l-1.56-2.13A7.491 7.491 0 0 1 2.15 3.306l2.622.285A1 1 0 0 0 5.795 3L6.86.585a7.56 7.56 0 0 1 2.28 0L10.205 3a1 1 0 0 0 1.023.59l2.622-.284a7.49 7.49 0 0 1 1.142 1.974l-1.56 2.13a1 1 0 0 0 0 1.18l1.56 2.13a7.489 7.489 0 0 1-1.142 1.974l-2.622-.285a1 1 0 0 0-1.023.59L9.14 15.415a7.56 7.56 0 0 1-2.28 0L5.795 13a1 1 0 0 0-1.023-.59l-2.622.284A7.489 7.489 0 0 1 1.01 10.72l1.559-2.13a1 1 0 0 0 0-1.18zM8 10a2 2 0 1 1 0-4 2 2 0 0 1 0 4z" />
    </g>
  ),
});
GearIcon.displayName = 'GearIcon';

export default GearIcon;
