/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const GiphyIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M4.556 13.444h7.777V7.611l1.556-1.555V15H3V1h5.833L7.278 2.556H4.556v10.888zm7.777-10.888V4.11h1.556v1.556H9.223V1h1.555v1.556h1.555z"
        clipRule="evenodd"
      />
    </g>
  ),
})
GiphyIcon.displayName = 'GiphyIcon'

export default GiphyIcon
