/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const GooglePhotosIcon = createIconComponent({
  content: (
    <g>
      <path d="M10.828 6.828A4 4 0 008 0v8a4 4 0 00-8 0h8a4 4 0 000 8V8a4 4 0 108 0H8a4 4 0 002.828-1.172z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
GooglePhotosIcon.displayName = 'GooglePhotosIcon'

export default GooglePhotosIcon
