/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const GoogleDriveIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M10.913 1H5.611l5.087 8.626H16L10.913 1zM16 10.231H5.894L3.27 14.753h10.106L16 10.23zM5.098 1.354l2.691 4.535-5.098 8.635L0 9.989l5.098-8.635z"
        clipRule="evenodd"
      />
    </g>
  ),
})
GoogleDriveIcon.displayName = 'GoogleDriveIcon'

export default GoogleDriveIcon
