/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const GooglePhotosIcon = createIconComponent({
  content: (
    <g>
      <path d="M9.475 5.975A3.5 3.5 0 007 0v7a3.5 3.5 0 10-7 0h7a3.5 3.5 0 100 7V7a3.5 3.5 0 107 0H7a3.5 3.5 0 002.475-1.025z" />
    </g>
  ),
});
GooglePhotosIcon.displayName = 'GooglePhotosIcon';

export default GooglePhotosIcon;
