/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const GridIcon = createIconComponent({
  content: (
    <g>
      <rect width="31" height="31" x="0.5" y="0.5" rx="3.5"></rect>
      <rect width="23" height="23" x="4.5" y="4.5" rx="11.5"></rect>
      <rect width="15" height="15" x="8.5" y="8.5" rx="3.5"></rect>
      <path d="M2 2l28.284 28.284m0-28.284L2 30.284"></path>
    </g>
  ),
});
GridIcon.displayName = 'GridIcon';

export default GridIcon;
