/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const HamburgerIcon = createIconComponent({
  content: (
    <g>
      <path d="M6 2h8a1 1 0 110 2H6V2zM1 3a1 1 0 011-1h4v2H2a1 1 0 01-1-1zm5 4h8a1 1 0 110 2H6V7zM1 8a1 1 0 011-1h4v2H2a1 1 0 01-1-1zm5 4h8a1 1 0 110 2H6v-2zm-5 1a1 1 0 011-1h4v2H2a1 1 0 01-1-1z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
HamburgerIcon.displayName = 'HamburgerIcon'

export default HamburgerIcon
