
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HashtagIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M6.141.01a1 1 0 0 1 .849 1.132L6.58 4h3.98L11.01.859a1 1 0 1 1 1.98.283L12.58 4H15a1 1 0 1 1 0 2h-2.704l-.572 4H14a1 1 0 0 1 0 2h-2.562l-.448 3.141a1 1 0 0 1-1.98-.283L9.418 12h-3.98L4.99 15.14a1 1 0 0 1-1.98-.283L3.418 12H1a1 1 0 1 1 0-2h2.704l.571-4H2a1 1 0 1 1 0-2h2.561L5.01.859A1 1 0 0 1 6.141.01zM6.296 6l-.572 4h3.98l.571-4h-3.98z" />
    </g>
  ),
});
HashtagIcon.displayName = 'HashtagIcon';

export default HashtagIcon;
