/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HeadingIcon = createIconComponent({
  content: (
    <g>
      <path d="M10 12.595H7.82V6.998H2.19v5.597H0V0h2.189v5.242H7.82V0H10v12.595z" />
    </g>
  ),
});
HeadingIcon.displayName = 'HeadingIcon';

export default HeadingIcon;
