/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HeadingIcon = createIconComponent({
  content: (
    <g>
      <path d="M12.796 14.086h-2.092v-5.37H5.3v5.37H3.2V2h2.1v5.03h5.404V2h2.092v12.086z"></path>
    </g>
  ),
});
HeadingIcon.displayName = 'HeadingIcon';

export default HeadingIcon;
