/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const HeadingIcon = createIconComponent({
  content: (
    <g>
      <path d="M10.146 8.989H5.893V14H3V2h2.893v4.764h4.253V2h2.884v12h-2.884V8.989z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
HeadingIcon.displayName = 'HeadingIcon'

export default HeadingIcon
