/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HeartOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M7.266 2.386A4.615 4.615 0 004.565 1.5C2.263 1.5.46 3.21.46 5.396c0 2.674 2.535 4.859 6.375 8.169l.434.373a1 1 0 001.305 0l.433-.373c3.84-3.31 6.375-5.495 6.375-8.169 0-2.185-1.801-3.896-4.103-3.896-.986 0-1.942.331-2.701.886a4.29 4.29 0 00-.657.591 4.29 4.29 0 00-.656-.591zm.76 10.046c1.952-1.683 3.447-2.976 4.472-4.167 1.011-1.175 1.385-2.05 1.385-2.869C13.883 4.112 12.827 3 11.28 3c-.873 0-1.714.393-2.243.98L7.922 5.22 6.808 3.98A3.083 3.083 0 004.565 3C3.017 3 1.96 4.112 1.96 5.396c0 .819.374 1.694 1.386 2.869 1.025 1.19 2.52 2.484 4.473 4.167l.102.088.103-.088z"
        clipRule="evenodd"
      />
    </g>
  ),
});
HeartOutlineIcon.displayName = 'HeartOutlineIcon';

export default HeartOutlineIcon;
