/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const HideIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_389_219)">
        <path d="M16 8s-.506.777-1.372 1.746c-.709-.468-1.706-1.012-3.014-1.727l-.632-.345a3 3 0 00-4.221-2.407c-.318-.195-.624-.385-.918-.568-.692-.43-1.32-.821-1.89-1.137C5.14 2.67 6.523 2 8 2c4.418 0 8 6 8 6zm-8 5.5c1.26 0 2.45-.447 3.51-1.086-.82-.382-1.763-.89-2.84-1.49a3.001 3.001 0 01-3.526-2.003C3.312 7.858 1.98 7.082 1.097 6.44.4 7.33 0 8 0 8s3.582 5.5 8 5.5zM.67 5.12a1 1 0 01.99-1.738l13.789 7.862a1 1 0 11-.99 1.737L.67 5.12z" />
      </g>
      <defs>
        <clipPath id="clip0_389_219">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
})
HideIcon.displayName = 'HideIcon'

export default HideIcon
