
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HomeIcon = createIconComponent({
  content: (
    <g>
      <path d="M14.5 7.793a.5.5 0 0 0-.5.5v5.667a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V8.293a.5.5 0 0 0-.5-.5h-.293a.5.5 0 0 1-.353-.854L7.646.146a.5.5 0 0 1 .708 0l6.792 6.793a.5.5 0 0 1-.353.854H14.5z" />
    </g>
  ),
});
HomeIcon.displayName = 'HomeIcon';

export default HomeIcon;
