/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HomeIcon = createIconComponent({
  content: (
    <g>
      <path d="M14.5 7.793a.5.5 0 00-.5.5v5.667a.5.5 0 01-.5.5h-3a.5.5 0 01-.5-.5v-3a.5.5 0 00-.5-.5h-3a.5.5 0 00-.5.5v3a.5.5 0 01-.5.5h-3a.5.5 0 01-.5-.5V8.293a.5.5 0 00-.5-.5h-.293a.5.5 0 01-.353-.854L7.646.146a.5.5 0 01.708 0l6.792 6.793a.5.5 0 01-.353.854H14.5z"></path>
    </g>
  ),
});
HomeIcon.displayName = 'HomeIcon';

export default HomeIcon;
