/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HomeIcon = createIconComponent({
  content: (
    <g>
      <path d="M14.5 8.182a.5.5 0 00-.5.5V14.5a.5.5 0 01-.5.5h-3a.5.5 0 01-.5-.5v-3.09a.5.5 0 00-.5-.5h-3a.5.5 0 00-.5.5v3.09a.5.5 0 01-.5.5h-3a.5.5 0 01-.5-.5V8.682a.5.5 0 00-.5-.5h-.312a.5.5 0 01-.357-.85L7.642.366a.5.5 0 01.715 0l6.812 6.966a.5.5 0 01-.357.85H14.5z" />
    </g>
  ),
});
HomeIcon.displayName = 'HomeIcon';

export default HomeIcon;
