
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const HotkeysIcon = createIconComponent({
  content: (
    <g>
      <path d="M6 4H4v2h2V4zM7 4h2v2H7V4zM12 4h-2v2h2V4zM4 7h2v2H4V7zM9 7H7v2h2V7zM10 7h2v2h-2V7zM12 10H4v2h8v-2z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M0 4a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3V4zm3-1h10a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z" />
    </g>
  ),
});
HotkeysIcon.displayName = 'HotkeysIcon';

export default HotkeysIcon;
