import snap from 'jest-auto-snapshots';
import ChevronUp from './ChevronUp';
import ChevronDown from './ChevronDown';
import Refresh from './Refresh';
import ArrowDown from './ArrowDown';
import ArrowLeft from './ArrowLeft';
import ArrowRight from './ArrowRight';
import ArrowUp from './ArrowUp';
import Camera from './Camera';
import ChartLine from './ChartLine';
import Clock from './Clock';
import Compare from './Compare';
import Emoji from './Emoji';
import Facebook from './Facebook';
import Flag from './Flag';
import Folder from './Folder';
import Gear from './Gear';
import GooglePlus from './GooglePlus';
import Instagram from './Instagram';
import Link from './Link';
import LinkedIn from './LinkedIn';
import List from './List';
import Locked from './Locked';
import Message from './Message';
import Location from './Location';
import Messenger from './Messenger';
import More from './More';
import Pause from './Pause';
import Pencil from './Pencil';
import People from './People';
import Person from './Person';
import Pinterest from './Pinterest';
import Plus from './Plus';
import Return from './Return';
import Sidebar from './Sidebar';
import Tag from './Tag';
import Twitter from './Twitter';
import Unlocked from './Unlocked';
import Warning from './Warning';

snap(ChevronUp, './ChevronUp.jsx');
snap(ChevronDown, './ChevronDown.jsx');
snap(Refresh, './Refresh.jsx');
snap(ArrowDown, './ArrowDown.jsx');
snap(ArrowLeft, './ArrowLeft.jsx');
snap(ArrowRight, './ArrowRight.jsx');
snap(ArrowUp, './ArrowUp.jsx');
snap(Camera, './Camera.jsx');
snap(ChartLine, './ChartLine.jsx');
snap(Clock, './Clock.jsx');
snap(Compare, './Compare.jsx');
snap(Emoji, './Emoji.jsx');
snap(Facebook, './Facebook.jsx');
snap(Flag, './Flag.jsx');
snap(Folder, './Folder.jsx');
snap(Gear, './Gear.jsx');
snap(GooglePlus, './GooglePlus.jsx');
snap(Instagram, './Instagram.jsx');
snap(Link, './Link.jsx');
snap(LinkedIn, './LinkedIn.jsx');
snap(List, './List.jsx');
snap(Location, './Location.jsx');
snap(Locked, './Locked.jsx');
snap(Message, './Message.jsx');
snap(Messenger, './Messenger.jsx');
snap(More, './More.jsx');
snap(Pause, './Pause.jsx');
snap(Pencil, './Pencil.jsx');
snap(People, './People.jsx');
snap(Person, './Person.jsx');
snap(Pinterest, './Pinterest.jsx');
snap(Plus, './Plus.jsx');
snap(Return, './Return.jsx');
snap(Sidebar, './Sidebar.jsx');
snap(Tag, './Tag.jsx');
snap(Twitter, './Twitter.jsx');
snap(Unlocked, './Unlocked.jsx');
snap(Warning, './Warning.jsx');
