/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ImageIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M.554 0h14.892c.304 0 .554.248.554.554V11.09c0 .306-.25.555-.554.555H.554A.556.556 0 010 11.089V.554C0 .248.25 0 .554 0zm3.198 2.85a1.475 1.475 0 11.002 2.95 1.475 1.475 0 01-.002-2.95zM1.283 1.281h13.434v7.481c-2.678-.467-4.087-4.23-5.768-4.23-1.791 0-4.168 4.23-5.45 4.23-1.089 0-1.193-1.12-2.216-1.627V1.282z"
        clipRule="evenodd"
      />
    </g>
  ),
});
ImageIcon.displayName = 'ImageIcon';

export default ImageIcon;
