/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ImportIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M10.589 5.597a1 1 0 010 1.414l-3.581 3.581-3.58-3.58A1 1 0 014.84 5.596l1.167 1.167v-4.77a1 1 0 112 0v4.77l1.166-1.167a1 1 0 011.415 0z"
        clipRule="evenodd"
      />
      <path
        fillRule="evenodd"
        d="M.875 14C.392 14 0 13.552 0 13V2c0-.552.392-1 .875-1H2.5a1 1 0 010 2H2v9h10V3h-.5a1 1 0 110-2h1.625c.483 0 .875.448.875 1v11c0 .552-.392 1-.875 1H.875z"
        clipRule="evenodd"
      />
    </g>
  ),
});
ImportIcon.displayName = 'ImportIcon';

export default ImportIcon;
