/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const InfoIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 0a8 8 0 110 16A8 8 0 018 0zM7 11.5a1 1 0 102 0v-4a1 1 0 10-2 0v4zm1-6a1 1 0 110-2 1 1 0 010 2z"
        clipRule="evenodd"
      />
    </g>
  ),
})
InfoIcon.displayName = 'InfoIcon'

export default InfoIcon
