/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const InstagramDmIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M1.155 2.578C.438 2.025.818.85 1.714.85h12.833c.687 0 1.137.74.84 1.377L9.414 15.006c-.395.844-1.61.666-1.759-.259L6.334 6.58l-5.18-4.002zm2.177-.212L7.07 5.253l4.981-2.887H3.332zm9.85 1.084l-4.355 9.318-1.005-6.212 5.36-3.106z"
        clipRule="evenodd"
      />
    </g>
  ),
});
InstagramDmIcon.displayName = 'InstagramDmIcon';

export default InstagramDmIcon;
