/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const InstagramCommentIcon = createIconComponent({
  content: (
    <g>
      <path d="M11.477 12.992a6.5 6.5 0 112.015-2.015L14.5 14l-3.023-1.008z" />
    </g>
  )
});
InstagramCommentIcon.displayName = 'InstagramCommentIcon';

export default InstagramCommentIcon;
