/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const InstagramGridIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M13 0H3a3 3 0 00-3 3v10a3 3 0 003 3h10a3 3 0 003-3V3a3 3 0 00-3-3zm-1.668 1.8H13A1.2 1.2 0 0114.2 3v1.668h-2.868V1.8zm-1.8 0H6.468v2.868h3.064V1.8zm-4.864 0H3A1.2 1.2 0 001.8 3v1.668h2.868V1.8zM1.8 6.468v3.064h2.868V6.468H1.8zm0 4.864V13A1.2 1.2 0 003 14.2h1.668v-2.868H1.8zM6.468 14.2h3.064v-2.868H6.468V14.2zm4.864 0H13a1.2 1.2 0 001.2-1.2v-1.668h-2.868V14.2zM14.2 9.532V6.468h-2.868v3.064H14.2zm-7.732 0V6.468h3.064v3.064H6.468z"
        clipRule="evenodd"
      />
    </g>
  ),
});
InstagramGridIcon.displayName = 'InstagramGridIcon';

export default InstagramGridIcon;
