/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const InstagramGridIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M11.375 0h-8.75A2.625 2.625 0 000 2.625v8.75A2.625 2.625 0 002.625 14h8.75A2.625 2.625 0 0014 11.375v-8.75A2.625 2.625 0 0011.375 0zm-1.46 1.575h1.46c.58 0 1.05.47 1.05 1.05v1.46h-2.51v-2.51zm-1.574 0H5.659v2.51h2.682v-2.51zm-4.257 0H2.625c-.58 0-1.05.47-1.05 1.05v1.46h2.51v-2.51zM1.575 5.659v2.682h2.51V5.659h-2.51zm0 4.257v1.459c0 .58.47 1.05 1.05 1.05h1.46v-2.51h-2.51zm4.084 2.509h2.682v-2.51H5.659v2.51zm4.257 0h1.459c.58 0 1.05-.47 1.05-1.05v-1.46h-2.51v2.51zm2.509-4.084V5.659h-2.51v2.682h2.51zm-6.766 0V5.659h2.682v2.682H5.659z"
        clipRule="evenodd"
      />
    </g>
  ),
})
InstagramGridIcon.displayName = 'InstagramGridIcon'

export default InstagramGridIcon
