/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const LayoutIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M0 4.5A4.5 4.5 0 014.5 0h7A4.5 4.5 0 0116 4.5v7a4.5 4.5 0 01-4.5 4.5h-7A4.5 4.5 0 010 11.5v-7zM4.5 2A2.5 2.5 0 002 4.5v7A2.5 2.5 0 004.5 14H7V2H4.5zM9 2v5h5V4.5A2.5 2.5 0 0011.5 2H9zm5 7H9v5h2.5a2.5 2.5 0 002.5-2.5V9z"
        clipRule="evenodd"
      />
    </g>
  ),
});
LayoutIcon.displayName = 'LayoutIcon';

export default LayoutIcon;
