/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const LayoutIcon = createIconComponent({
  content: (
    <g>
      <path d="M8 1.438V8m0 0v6.125M8 8h6.125M4.5 15h7a3.5 3.5 0 003.5-3.5v-7A3.5 3.5 0 0011.5 1h-7A3.5 3.5 0 001 4.5v7A3.5 3.5 0 004.5 15z" />
    </g>
  ),
});
LayoutIcon.displayName = 'LayoutIcon';

export default LayoutIcon;
