
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const LinkedInIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M13.634 13.634h-2.372V9.921c0-.886-.016-2.025-1.233-2.025-1.235 0-1.424.965-1.424 1.96v3.778H6.234V5.998H8.51v1.044h.032c.316-.6 1.09-1.234 2.245-1.234 2.403 0 2.847 1.582 2.847 3.638v4.188zM3.559 4.954a1.376 1.376 0 1 1 0-2.752 1.376 1.376 0 0 1 0 2.753zm-1.187 8.68h2.373V5.998H2.372v7.636zM14.816 0H1.18C.529 0 0 .516 0 1.153v13.692C0 15.483.53 16 1.181 16h13.635c.652 0 1.184-.517 1.184-1.155V1.153C16 .516 15.468 0 14.816 0z" />
    </g>
  ),
});
LinkedInIcon.displayName = 'LinkedInIcon';

export default LinkedInIcon;
