
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const LinkIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0)">
        <path fillRule="evenodd" clipRule="evenodd" d="M7.464 5.485l2.9-2.9a2 2 0 1 1 2.828 2.83l-2.9 2.899 1.415 1.414 2.9-2.9A4 4 0 0 0 8.95 1.172l-2.9 2.9 1.414 1.413zM6.05 6.9L4.636 5.486 1.172 8.95a4 4 0 0 0 5.656 5.657l3.465-3.465-1.414-1.414-3.465 3.464a2 2 0 0 1-2.828-2.828L6.05 6.899z" />
        <rect x="5" y="12.335" width="2" height="10" rx="1" transform="rotate(-135 5 12.335)" />
      </g>
      <defs>
        <clipPath id="clip0">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>

    </g>
  ),
});
LinkIcon.displayName = 'LinkIcon';

export default LinkIcon;
