
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ListIcon = createIconComponent({
  content: (
    <g>
      <path d="M6 2h8a1 1 0 1 1 0 2H6V2zM1 3a1 1 0 0 1 1-1h2v2H2a1 1 0 0 1-1-1zM6 7h8a1 1 0 1 1 0 2H6V7zM1 8a1 1 0 0 1 1-1h2v2H2a1 1 0 0 1-1-1zM6 12h8a1 1 0 1 1 0 2H6v-2zM1 13a1 1 0 0 1 1-1h2v2H2a1 1 0 0 1-1-1z" />
    </g>
  ),
});
ListIcon.displayName = 'ListIcon';

export default ListIcon;
