
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const LoadIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12zm0 2A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
      <defs>
        <radialGradient id="paint0_angular" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="matrix(0 8 -8 0 8 8)">
          <stop />
          <stop offset="0.602" />
          <stop offset="0.707" stopOpacity="0.906" />
          <stop offset="0.801" stopColor="#fff" stopOpacity="0" />
          <stop offset="1" stopColor="#fff" stopOpacity="0" />
        </radialGradient>
      </defs>

    </g>
  ),
});
LoadIcon.displayName = 'LoadIcon';

export default LoadIcon;
