/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const LocationIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M10.06 13.392C12.236 10.713 14 8.542 14 6A6 6 0 002 6c0 2.541 1.764 4.713 3.94 7.392C6.6 14.206 7.3 15.067 8 16a85.26 85.26 0 012.06-2.608zM8 9a3 3 0 100-6 3 3 0 000 6z"
        clipRule="evenodd"
      ></path>
    </g>
  ),
});
LocationIcon.displayName = 'LocationIcon';

export default LocationIcon;
