/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const LocationPinIcon = createIconComponent({
  content: (
    <g>
      <path d="M8.001 1c3.386 0 5.306 2.919 4.59 6.022C12.082 9.232 9.002 15 8.002 15c-.935 0-4.072-5.77-4.59-7.978C2.691 3.949 4.596 1 8.001 1zM8 7.396a1.77 1.77 0 100-3.54 1.77 1.77 0 000 3.54z" />
    </g>
  ),
})
LocationPinIcon.displayName = 'LocationPinIcon'

export default LocationPinIcon
