/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const MastodonIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_3488_2180)">
        <path
          fillRule="evenodd"
          d="M11.19 12.195c2.016-.24 3.77-1.475 3.99-2.603.348-1.778.32-4.339.32-4.339 0-3.47-2.286-4.488-2.286-4.488C12.062.238 10.083.017 8.027 0h-.05C5.92.017 3.942.238 2.79.765c0 0-2.285 1.017-2.285 4.488l-.002.662c-.004.64-.007 1.35.011 2.091.083 3.394.626 6.74 3.78 7.57 1.454.383 2.703.463 3.709.408 1.823-.1 2.847-.647 2.847-.647l-.06-1.317s-1.303.41-2.767.36c-1.45-.05-2.98-.156-3.215-1.928a3.614 3.614 0 01-.033-.496s1.424.346 3.228.428c1.103.05 2.137-.064 3.188-.189zm1.614-2.47V5.522c0-.859-.22-1.541-.662-2.046-.455-.505-1.051-.764-1.791-.764-.857 0-1.505.327-1.934.983L8 4.39l-.417-.695c-.429-.656-1.077-.983-1.933-.983-.74 0-1.337.259-1.792.764-.442.505-.661 1.187-.661 2.046v4.203H4.87v-4.08c0-.859.364-1.295 1.091-1.295.804 0 1.207.517 1.207 1.541v2.233h1.664V5.89c0-1.024.403-1.541 1.207-1.541.727 0 1.091.436 1.091 1.296v4.079h1.673z"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="clip0_3488_2180">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
})
MastodonIcon.displayName = 'MastodonIcon'

export default MastodonIcon
