/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M.408 1.881C-.372 1.278.042 0 1.016 0h13.968c.748 0 1.239.805.914 1.498l-6.5 13.91c-.43.919-1.752.725-1.915-.282l-1.438-8.89L.408 1.882zm2.37-.231l4.067 3.142 5.422-3.142H2.778zm10.72 1.18l-4.74 10.142L7.664 6.21 13.5 2.83z"
        clipRule="evenodd"
      />
    </g>
  ),
});
MessageOutlineIcon.displayName = 'MessageOutlineIcon';

export default MessageOutlineIcon;
