/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessengerIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 0C3.582 0 0 3.316 0 7.407c0 2.332 1.163 4.41 2.981 5.769V16l2.724-1.495c.727.201 1.497.31 2.295.31 4.418 0 8-3.317 8-7.408C16 3.317 12.418 0 8 0zm.795 9.975L6.758 7.803 2.783 9.975l4.372-4.642 2.087 2.173 3.926-2.173-4.373 4.642z"
        clipRule="evenodd"
      ></path>
    </g>
  ),
});
MessengerIcon.displayName = 'MessengerIcon';

export default MessengerIcon;
