/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageRoundFilledIcon = createIconComponent({
  content: (
    <g>
      <path d="M8 .5a7.5 7.5 0 103.793 13.972l2.494.831a.804.804 0 001.016-1.016l-.831-2.495A7.5 7.5 0 008 .5z" />
    </g>
  ),
});
MessageRoundFilledIcon.displayName = 'MessageRoundFilledIcon';

export default MessageRoundFilledIcon;
