/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageFilledIcon = createIconComponent({
  content: (
    <g>
      <path d="M.89 0C.035 0-.327 1.119.356 1.646L4.05 4.5l6.356-1.976-4.868 4.47 1.01 6.242c.142.88 1.3 1.05 1.675.246l5.688-12.17C14.195.703 13.765 0 13.111 0H.89z" />
    </g>
  ),
});
MessageFilledIcon.displayName = 'MessageFilledIcon';

export default MessageFilledIcon;
