/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageFilledIcon = createIconComponent({
  content: (
    <g>
      <path d="M1.89 1c-.854 0-1.216 1.119-.533 1.646L5.05 5.5l6.356-1.976-4.868 4.47 1.01 6.242c.142.88 1.3 1.05 1.675.246l5.688-12.17c.284-.608-.146-1.312-.8-1.312H1.89z" />
    </g>
  ),
});
MessageFilledIcon.displayName = 'MessageFilledIcon';

export default MessageFilledIcon;
