/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageRoundOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M11.23 12.308l1.298.243-.22-1.32.243-.351a5.385 5.385 0 10-1.671 1.671l.35-.243zm3.43 1.67a.538.538 0 01-.682.681l-2.233-.744a7 7 0 112.17-2.17l.744 2.233z"
        clipRule="evenodd"
      />
    </g>
  ),
});
MessageRoundOutlineIcon.displayName = 'MessageRoundOutlineIcon';

export default MessageRoundOutlineIcon;
