/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageFilledIcon = createIconComponent({
  content: (
    <g>
      <path d="M1.016 0C.042 0-.372 1.278.408 1.881l4.221 3.262 7.264-2.258-5.564 5.108 1.154 7.133c.163 1.007 1.485 1.2 1.915.282l6.5-13.91C16.223.805 15.732 0 14.984 0H1.016z" />
    </g>
  ),
});
MessageFilledIcon.displayName = 'MessageFilledIcon';

export default MessageFilledIcon;
