/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const MessageSquareFilledIcon = createIconComponent({
  content: (
    <g>
      <path d="M0 2.116C0 1.5.512 1 1.143 1h13.714C15.488 1 16 1.5 16 2.116v7.812c0 .616-.512 1.116-1.143 1.116H5.714c-.853 0-3.298 1.865-4.72 2.811-.522.347-.994.037-.994-.58V2.117z" />
    </g>
  ),
})
MessageSquareFilledIcon.displayName = 'MessageSquareFilledIcon'

export default MessageSquareFilledIcon
