/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MessageOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M1.137 2.496C.454 1.969.817.85 1.669.85h12.222c.654 0 1.084.704.8 1.311l-5.688 12.17c-.376.805-1.533.635-1.675-.245l-1.259-7.78-4.932-3.81zm2.074-.202l3.558 2.75 4.745-2.75H3.21zm9.38 1.032L8.444 12.2l-.958-5.917 5.105-2.958z"
        clipRule="evenodd"
      />
    </g>
  ),
});
MessageOutlineIcon.displayName = 'MessageOutlineIcon';

export default MessageOutlineIcon;
