
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MoreIcon = createIconComponent({
  content: (
    <g>
      <path d="M10 2a2 2 0 11-4 0 2 2 0 014 0zm-2 8a2 2 0 100-4 2 2 0 000 4zm0 6a2 2 0 100-4 2 2 0 000 4z" />

    );
    }

    export default Icon;
    </g>
  ),
});
MoreIcon.displayName = 'MoreIcon';

export default MoreIcon;
