
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const MovieIcon = createIconComponent({
  content: (
    <g>
      <path d="M11.77 6.41V4.178A1.93 1.93 0 009.842 2.25H2.178A1.93 1.93 0 00.25 4.178v7.664a1.93 1.93 0 001.928 1.928h7.664a1.93 1.93 0 001.928-1.928V9.61l2.372 1.976c.807.673 1.468.365 1.468-.696V5.13c0-1.068-.657-1.372-1.468-.696L11.77 6.41z" />

    );
    }

    export default Icon;
    </g>
  ),
});
MovieIcon.displayName = 'MovieIcon';

export default MovieIcon;
