/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const NegativeIcon = createIconComponent({
  content: (
    <g>
      <path d="M6.5 2a1.5 1.5 0 113 0v7.5a1.5 1.5 0 01-3 0V2zm0 12a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0z" />
    </g>
  ),
});
NegativeIcon.displayName = 'NegativeIcon';

export default NegativeIcon;
