
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const NegativeIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm7 0a1 1 0 0 1 2 0v5a1 1 0 1 1-2 0V4zm1 7a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
    </g>
  ),
});
NegativeIcon.displayName = 'NegativeIcon';

export default NegativeIcon;
