/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const OnedriveIcon = createIconComponent({
  content: (
    <g>
      <path d="M.719 11.537a3.998 3.998 0 013.23-6.285 5 5 0 019.02 1.507 3.25 3.25 0 01-.22 6.492H4a3.994 3.994 0 01-3.28-1.714z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
OnedriveIcon.displayName = 'OnedriveIcon'

export default OnedriveIcon
