
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const OrderIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4.784.3l-.103-.387A1.5 1.5 0 0 0 3.231 2.8H2a.5.5 0 0 0 0 1h1.232a.5.5 0 0 1 .483.371l1.703 6.387a1 1 0 0 0 .966.742H7a1 1 0 1 0 0 2 1 1 0 0 0 0-2h4a1 1 0 1 0 0 2 1 1 0 0 0 0-2h1.5a.5.5 0 0 0 0-1H6.384l-.267-1h6.011a.5.5 0 0 0 .479-.356l1.2-4a.5.5 0 0 0-.479-.644H4.784z" />
    </g>
  ),
});
OrderIcon.displayName = 'OrderIcon';

export default OrderIcon;
