/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PatreonIcon = createIconComponent({
  content: (
    <g>
      <path d="M1 2h3v13H1V2zm15 5.5a5.5 5.5 0 11-11 0 5.5 5.5 0 0111 0z" />
    </g>
  ),
});
PatreonIcon.displayName = 'PatreonIcon';

export default PatreonIcon;
