/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PatreonIcon = createIconComponent({
  content: (
    <g>
      <path d="M0 0h3v13H0V0zm15 5.5a5.5 5.5 0 11-11 0 5.5 5.5 0 0111 0z"></path>
    </g>
  ),
});
PatreonIcon.displayName = 'PatreonIcon';

export default PatreonIcon;
