/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PaypalIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_2377_1833)">
        <path d="M14.667 6.507c0 .358-.044.723-.113 1.085-.565 2.946-2.497 3.964-4.966 3.964h-.381a.615.615 0 00-.606.526l-.535 3.393a.616.616 0 01-.605.525H5.637a.423.423 0 01-.419-.488l.924-5.92.041-.037H7.62c3.49 0 5.673-1.746 6.315-5.046.542.543.732 1.251.732 1.998zM5.189 9.342c.078-.55.306-.785.924-.786l1.506-.001c3.05 0 4.799-1.394 5.349-4.26C13.501 1.539 11.567 0 8.948 0H4.05a.704.704 0 00-.692.6c-1.536 9.89-1.98 12.405-2.025 13.173a.425.425 0 00.423.448h2.66l.772-4.879z" />
      </g>
      <defs>
        <clipPath id="clip0_2377_1833">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
});
PaypalIcon.displayName = 'PaypalIcon';

export default PaypalIcon;
