/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const PencilIcon = createIconComponent({
  content: (
    <g>
      <path d="M14.142.837a1 1 0 00-1.414 0l-.707.707 2.121 2.122.707-.708a1 1 0 000-1.414l-.707-.707zm-2.828 1.414l2.121 2.122-8.485 8.485-2.381 1.19a.694.694 0 01-.931-.93l1.19-2.381 8.486-8.486z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
PencilIcon.displayName = 'PencilIcon'

export default PencilIcon
