
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PercentageDownIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M3.693 3.693a1 1 0 0 1 1.414 0L11.4 9.986V6a1 1 0 1 1 2 0v7.4H6a1 1 0 1 1 0-2h3.986L3.693 5.107a1 1 0 0 1 0-1.414z" />
    </g>
  ),
});
PercentageDownIcon.displayName = 'PercentageDownIcon';

export default PercentageDownIcon;
