/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PercentageUpIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M5 3.6a1 1 0 011-1h7.4V10a1 1 0 11-2 0V6.014l-6.293 6.293a1 1 0 01-1.414-1.414L9.986 4.6H6a1 1 0 01-1-1z"
        clipRule="evenodd"
      />
    </g>
  ),
});
PercentageUpIcon.displayName = 'PercentageUpIcon';

export default PercentageUpIcon;
