/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PinIcon = createIconComponent({
  content: (
    <g>
      <path d="M4.892 0c-.515 0-.764.637-.388.993l1.095.932-.948 5.751L3.14 9.38c-.32.371-.06.951.428.951h3.577v3.8a.58.58 0 00.037.201l.55 1.482a.282.282 0 00.53 0l.55-1.482a.58.58 0 00.037-.202v-3.799h3.581c.487 0 .748-.578.429-.95l-1.516-1.713-.947-5.746 1.09-.928C11.864.638 11.615 0 11.1 0H4.892z" />
    </g>
  ),
});
PinIcon.displayName = 'PinIcon';

export default PinIcon;
