
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PlaceholderIcon = createIconComponent({
  content: (
    <g>
      <rect width="16" height="16" rx="4" />
    </g>
  ),
});
PlaceholderIcon.displayName = 'PlaceholderIcon';

export default PlaceholderIcon;
