
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PlaceholderIcon = createIconComponent({
  content: (
    <g>
      <path d="M0 4a4 4 0 014-4h8a4 4 0 014 4v8a4 4 0 01-4 4H4a4 4 0 01-4-4V4z" />

    );
    }

    export default Icon;
    </g>
  ),
});
PlaceholderIcon.displayName = 'PlaceholderIcon';

export default PlaceholderIcon;
