/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PlayIcon = createIconComponent({
  content: (
    <g>
      <path d="M13.654 9.444a1.654 1.654 0 000-2.888l-7.616-4.33C4.91 1.584 3.5 2.386 3.5 3.669v8.662c0 1.283 1.41 2.085 2.538 1.443l7.616-4.33z" />
    </g>
  ),
});
PlayIcon.displayName = 'PlayIcon';

export default PlayIcon;
