/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PlayIcon = createIconComponent({
  content: (
    <g>
      <path d="M11.461 8.962c.719-.427.719-1.497 0-1.924L6.615 4.15C5.897 3.723 5 4.257 5 5.113v5.774c0 .855.897 1.39 1.615.963l4.846-2.888z" />
    </g>
  ),
});
PlayIcon.displayName = 'PlayIcon';

export default PlayIcon;
