/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PlayRoundIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 16A8 8 0 108 0a8 8 0 000 16zm2.872-8.727a.902.902 0 010 1.575L6.718 11.21c-.615.35-1.385-.087-1.385-.787V5.698c0-.7.77-1.137 1.385-.787l4.154 2.362z"
        clipRule="evenodd"
      />
    </g>
  ),
});
PlayRoundIcon.displayName = 'PlayRoundIcon';

export default PlayRoundIcon;
