
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PlusIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" d="M16 8A8 8 0 110 8a8 8 0 0116 0zM8 3a1 1 0 00-1 1v8a1 1 0 102 0V9h3a1 1 0 100-2H9V4a1 1 0 00-1-1zM4 9h2V7H4a1 1 0 000 2z" clipRule="evenodd" />

    );
    }

    export default Icon;
    </g>
  ),
});
PlusIcon.displayName = 'PlusIcon';

export default PlusIcon;
