
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PostIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M2 2.2a1 1 0 0 0-1 1v9.586a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3.2a1 1 0 0 0-1-1H2zm4.828 2.78a.695.695 0 0 0 0 1.391h5.61a.695.695 0 0 0 0-1.39h-5.61zm0 2.318a.695.695 0 1 0 0 1.39h5.61a.695.695 0 1 0 0-1.39h-5.61zm-.695 3.012c0-.383.311-.695.695-.695h5.61a.695.695 0 1 1 0 1.39h-5.61a.695.695 0 0 1-.695-.695z" />
    </g>
  ),
});
PostIcon.displayName = 'PostIcon';

export default PostIcon;
