
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const PublishIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M3.097 3.3L14.25 1.25 12.2 12.403 3.097 3.3zm4.217 10.922L1.25 8.158l3.28-.603 3.387 3.387-.603 3.28z" />
    </g>
  ),
});
PublishIcon.displayName = 'PublishIcon';

export default PublishIcon;
