
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const QrCodeIcon = createIconComponent({
  content: (
    <g>
      <path d="M3.795 3.545h.773a.25.25 0 0 1 .25.25v.773a.25.25 0 0 1-.25.25h-.773a.25.25 0 0 1-.25-.25v-.773a.25.25 0 0 1 .25-.25z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M1.5 1a.5.5 0 0 0-.5.5v5.364a.5.5 0 0 0 .5.5h5.364a.5.5 0 0 0 .5-.5V1.5a.5.5 0 0 0-.5-.5H1.5zm.773 1.773a.5.5 0 0 1 .5-.5H5.59a.5.5 0 0 1 .5.5V5.59a.5.5 0 0 1-.5.5H2.773a.5.5 0 0 1-.5-.5V2.773z" />
      <path d="M9.136 8.636h1.546a.5.5 0 0 1 .5.5v.273a.5.5 0 0 1-.5.5H9.136a.5.5 0 0 1-.5-.5v-.273a.5.5 0 0 1 .5-.5zM9.41 11.182h-.274a.5.5 0 0 0-.5.5V14.5a.5.5 0 0 0 .5.5h.273a.5.5 0 0 0 .5-.5v-2.818a.5.5 0 0 0-.5-.5zM11.682 13.727h.273a.5.5 0 0 1 .5.5v.273a.5.5 0 0 1-.5.5h-.273a.5.5 0 0 1-.5-.5v-.273a.5.5 0 0 1 .5-.5zM12.955 8.636a.5.5 0 0 0-.5.5v.273a.5.5 0 0 0 .5.5h.772v1.273h-2.045a.5.5 0 0 0-.5.5v.273a.5.5 0 0 0 .5.5h2.045V14.5a.5.5 0 0 0 .5.5h.273a.5.5 0 0 0 .5-.5V9.136a.5.5 0 0 0-.5-.5h-1.545zM11.432 3.545h.773a.25.25 0 0 1 .25.25v.773a.25.25 0 0 1-.25.25h-.773a.25.25 0 0 1-.25-.25v-.773a.25.25 0 0 1 .25-.25z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M8.636 1.5a.5.5 0 0 1 .5-.5H14.5a.5.5 0 0 1 .5.5v5.364a.5.5 0 0 1-.5.5H9.136a.5.5 0 0 1-.5-.5V1.5zm1.773.773a.5.5 0 0 0-.5.5V5.59a.5.5 0 0 0 .5.5h2.818a.5.5 0 0 0 .5-.5V2.773a.5.5 0 0 0-.5-.5H10.41z" />
      <path d="M4.568 11.182h-.773a.25.25 0 0 0-.25.25v.773c0 .138.112.25.25.25h.773a.25.25 0 0 0 .25-.25v-.773a.25.25 0 0 0-.25-.25z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M1.5 8.636a.5.5 0 0 0-.5.5V14.5a.5.5 0 0 0 .5.5h5.364a.5.5 0 0 0 .5-.5V9.136a.5.5 0 0 0-.5-.5H1.5zm.773 1.773a.5.5 0 0 1 .5-.5H5.59a.5.5 0 0 1 .5.5v2.818a.5.5 0 0 1-.5.5H2.773a.5.5 0 0 1-.5-.5V10.41z" />
    </g>
  ),
});
QrCodeIcon.displayName = 'QrCodeIcon';

export default QrCodeIcon;
