
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const QuestionIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M4 0a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4H4zm3.232 8.074c-.132.324-.199.76-.199 1.307h1.5l.024-.358c.043-.382.213-.716.51-1.002l.474-.45c.371-.36.63-.686.78-.98a2.08 2.08 0 0 0 .222-.943c0-.73-.228-1.294-.686-1.693-.457-.402-1.1-.603-1.927-.603-.82 0-1.47.21-1.946.632-.472.422-.713 1.006-.72 1.752h1.699c.008-.312.098-.556.27-.732.175-.18.408-.27.697-.27.61 0 .914.33.914.99 0 .22-.059.428-.176.628-.117.195-.354.45-.709.767-.352.313-.594.631-.727.955zm-.105 2.461a.852.852 0 0 0-.264.645c0 .258.086.47.258.638.176.168.406.252.691.252.286 0 .514-.084.686-.252a.846.846 0 0 0 .264-.638.843.843 0 0 0-.27-.645.931.931 0 0 0-.68-.258.952.952 0 0 0-.685.258z" />
    </g>
  ),
});
QuestionIcon.displayName = 'QuestionIcon';

export default QuestionIcon;
