/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ReelIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_3870_2359)">
        <path d="M9.001 0l1.96 3.611H6.895L4.934 0H9zm2.609 0c2.124 0 3.9 1.555 4.304 3.612H12.94L10.98 0h.63zM3.067.21C1.56.698.402 2 .087 3.61h4.828L3.067.21z" />
        <path
          fillRule="evenodd"
          d="M0 11.502V5.383h16v6.12C16 13.982 14.03 16 11.61 16H4.39C1.97 16 0 13.982 0 11.502zm6.693 1.49l3.765-2.06a.796.796 0 000-1.388L6.693 7.483c-.511-.28-1.13.1-1.13.694v4.122c0 .594.619.974 1.13.694z"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="clip0_3870_2359">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
});
ReelIcon.displayName = 'ReelIcon';

export default ReelIcon;
