
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const RefreshIcon = createIconComponent({
  content: (
    <g>
      <path d="M7 1a7 7 0 1 0 0 14h1a1 1 0 1 0 0-2H7a5 5 0 1 1 5-5h-1.793a.5.5 0 0 0-.353.854l2.793 2.793a.5.5 0 0 0 .707 0l2.793-2.793A.5.5 0 0 0 15.793 8H14a7 7 0 0 0-7-7z" />
    </g>
  ),
});
RefreshIcon.displayName = 'RefreshIcon';

export default RefreshIcon;
