/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from "react";
import createIconComponent from "../utils/createIconComponent";

const RefreshIcon = createIconComponent({
  content: (
    <g>
      <path d="M6.874 1.2a6.874 6.874 0 100 13.747h.982a.982.982 0 000-1.963h-.982a4.91 4.91 0 114.91-4.91h-1.761a.491.491 0 00-.347.838l2.742 2.742a.49.49 0 00.695 0l2.742-2.742a.491.491 0 00-.347-.838h-1.76A6.874 6.874 0 006.874 1.2z" />
    </g>
  ),
});
RefreshIcon.displayName = "RefreshIcon";

export default RefreshIcon;
