
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ReplyIcon = createIconComponent({
  content: (
    <g>
      <path d="M16 9.038H8.927V16H16V9.038z" />
      <path fillRule="evenodd" clipRule="evenodd" d="M0 0h13.805v6.949H6.837v6.962L0 13.925V0z" />
    </g>
  ),
});
ReplyIcon.displayName = 'ReplyIcon';

export default ReplyIcon;
