/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const ReplyIcon = createIconComponent({
  content: (
    <g>
      <path d="M16 9.038H8.927V16H16V9.038z" />
      <path
        fillRule="evenodd"
        d="M0 0h13.806v6.949h-6.97v6.962L0 13.925V0z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
ReplyIcon.displayName = 'ReplyIcon'

export default ReplyIcon
