
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ReplyIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M6.09 4.95L3.448 2.313 12.795 2l-4.83 4.83-6.085 6.09L0 11.04l6.09-6.09zm8.03-1.48L16 5.34l-6.09 6.09 2.641 2.637-9.346.314 4.83-4.83L14.12 3.47z" />
    </g>
  ),
});
ReplyIcon.displayName = 'ReplyIcon';

export default ReplyIcon;
