
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ReplyIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M12.354 2H2v10.444l5.128-.01V7.21h5.226V2zM8.696 8.778H14V14H8.696V8.778z" />
    </g>
  ),
});
ReplyIcon.displayName = 'ReplyIcon';

export default ReplyIcon;
