/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const RetweetIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3.544 0l3.469 3.324a.873.873 0 01.02 1.243.896.896 0 01-1.257.02L4.53 3.393v7.503h4.158c.491 0 .89.394.89.88 0 .485-.399.88-.89.88H4.1c-.717 0-1.347-.565-1.347-1.32V3.207L1.507 4.401A.896.896 0 01.25 4.38a.873.873 0 01.02-1.244L3.544 0zm2.879 1.224c0-.485.398-.88.889-.88H11.9c.717 0 1.347.565 1.347 1.32v8.129l1.246-1.194a.896.896 0 011.256.02.873.873 0 01-.02 1.244L12.457 13l-3.47-3.324a.873.873 0 01-.02-1.243.896.896 0 011.257-.02l1.245 1.194V2.104H7.313a.884.884 0 01-.89-.88z"
        clipRule="evenodd"
      />
    </g>
  ),
});
RetweetIcon.displayName = 'RetweetIcon';

export default RetweetIcon;
