/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const RetweetIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M4.101 2l3.035 3.068a.837.837 0 01.018 1.148.755.755 0 01-1.1.018l-1.09-1.102v6.926h3.638c.43 0 .778.364.778.812 0 .448-.348.812-.778.812H4.588c-.628 0-1.18-.521-1.18-1.218V4.96L2.32 6.062a.755.755 0 01-1.1-.018.837.837 0 01.018-1.148L4.1 2zm2.52 1.13c0-.448.347-.812.777-.812h4.014c.628 0 1.18.521 1.18 1.218v7.504l1.089-1.102a.755.755 0 011.1.018.837.837 0 01-.018 1.148L11.9 14l-3.035-3.068a.837.837 0 01-.018-1.148.755.755 0 011.1-.018l1.09 1.102V3.942H7.398c-.43 0-.778-.364-.778-.812z"
        clipRule="evenodd"
      />
    </g>
  ),
});
RetweetIcon.displayName = 'RetweetIcon';

export default RetweetIcon;
