/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SaveIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M1.75 0A1.75 1.75 0 000 1.75v10.5C0 13.216.784 14 1.75 14h10.5A1.75 1.75 0 0014 12.25V6.782a3.5 3.5 0 00-1.126-2.571L9.318.928A3.5 3.5 0 006.944 0H1.75zm8.363 5.689a.656.656 0 00-.976-.878L5.622 8.716l-.827-.689a.656.656 0 00-.84 1.008l1.798 1.499 4.36-4.845z"
        clipRule="evenodd"
      />
    </g>
  ),
});
SaveIcon.displayName = 'SaveIcon';

export default SaveIcon;
