
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SearchIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M9.5 10a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zm0 2a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11z" />
      <path d="M5.95 9l1.414 1.414-4.243 4.243a1 1 0 0 1-1.414-1.414L5.95 9z" />
    </g>
  ),
});
SearchIcon.displayName = 'SearchIcon';

export default SearchIcon;
