
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SearchIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" d="M9.5 10a3.5 3.5 0 100-7 3.5 3.5 0 000 7zm0 2a5.5 5.5 0 100-11 5.5 5.5 0 000 11z" clipRule="evenodd" />
      <path d="M5.95 9l1.414 1.414-4.243 4.243a1 1 0 01-1.414-1.414L5.95 9z" />

    );
    }

    export default Icon;
    </g>
  ),
});
SearchIcon.displayName = 'SearchIcon';

export default SearchIcon;
