/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShareArrowOutlineIcon = createIconComponent({
  content: (
    <g>
      <path d="M8.087 5.2l.656-.082v-.66l.002-2.027c0-.348.17-.554.32-.635.132-.07.28-.072.437.08l.522-.538-.522.537 5.534 5.373.523-.538-.522.538c.28.272.286.825.006 1.106l-5.542 5.572c-.158.158-.309.157-.442.087-.15-.08-.322-.286-.322-.637l.001-1.713v-.755l-.754.004c-3.48.02-5.709 1.16-7.123 2.466.34-2.821 1.314-4.688 2.503-5.914C4.746 6.04 6.49 5.402 8.087 5.201z" />
    </g>
  ),
});
ShareArrowOutlineIcon.displayName = 'ShareArrowOutlineIcon';

export default ShareArrowOutlineIcon;
