/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShareIcon = createIconComponent({
  content: (
    <g>
      <path d="M11.629 5.213a2.37 2.37 0 01-1.27-.368l-3.71 2.573a2.343 2.343 0 010 1.3l3.609 2.504a2.37 2.37 0 011.371-.435A2.364 2.364 0 0114 13.144a2.364 2.364 0 01-2.371 2.356 2.364 2.364 0 01-2.317-2.857l-3.7-2.567a2.371 2.371 0 01-1.241.349A2.364 2.364 0 012 8.068a2.364 2.364 0 012.371-2.356c.455 0 .88.128 1.242.349L9.34 3.474a2.345 2.345 0 01-.083-.618A2.364 2.364 0 0111.63.5 2.364 2.364 0 0114 2.856a2.364 2.364 0 01-2.371 2.357z" />
    </g>
  ),
});
ShareIcon.displayName = 'ShareIcon';

export default ShareIcon;
