/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShareArrowIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M0 13V7.5a1 1 0 012 0V13a1 1 0 001 1h10a1 1 0 001-1V7.5a1 1 0 112 0V13a3 3 0 01-3 3H3a3 3 0 01-3-3z"
        clipRule="evenodd"
      />
      <path
        fillRule="evenodd"
        d="M7.964 10.844A.844.844 0 017.121 10V3.23L4.744 5.606A.844.844 0 013.55 4.414L7.964 0l4.414 4.414a.844.844 0 01-1.193 1.193L8.808 3.229V10a.844.844 0 01-.844.844z"
        clipRule="evenodd"
      />
    </g>
  ),
});
ShareArrowIcon.displayName = 'ShareArrowIcon';

export default ShareArrowIcon;
