/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShareArrowIcon = createIconComponent({
  content: (
    <g>
      <path d="M8 12a.968.968 0 01-.713-.288A.964.964 0 017 11V3.85L5.125 5.725c-.2.2-.433.3-.7.3-.267 0-.508-.108-.725-.325a.929.929 0 01-.287-.712A.984.984 0 013.7 4.3L7.3.7c.1-.1.208-.17.325-.212a1.132 1.132 0 01.75 0A.888.888 0 018.7.7l3.6 3.6c.2.2.296.438.288.713a.97.97 0 01-.288.687c-.2.2-.438.304-.713.313a.925.925 0 01-.712-.288L9 3.85V11a.968.968 0 01-.288.713A.964.964 0 018 12zm-6 4c-.55 0-1.021-.196-1.413-.588A1.922 1.922 0 010 14V8c0-.283.096-.521.288-.713A.964.964 0 011 7c.283 0 .521.096.713.288.192.192.288.43.287.712v6h12V8c0-.283.096-.521.288-.713A.964.964 0 0115 7c.283 0 .521.096.713.288.192.192.288.43.287.712v6c0 .55-.196 1.021-.588 1.413A1.922 1.922 0 0114 16H2z" />
    </g>
  ),
});
ShareArrowIcon.displayName = 'ShareArrowIcon';

export default ShareArrowIcon;
