/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShareArrowIcon = createIconComponent({
  content: (
    <g>
      <path d="M8 11.5a.847.847 0 01-.624-.252.843.843 0 01-.251-.623V4.37l-1.64 1.64a.84.84 0 01-.613.263c-.233 0-.445-.095-.635-.284a.812.812 0 01-.25-.623.861.861 0 01.25-.602l3.15-3.15a.763.763 0 01.285-.186.99.99 0 01.656 0 .777.777 0 01.285.186l3.15 3.15a.816.816 0 01.252.623.85.85 0 01-.253.602.894.894 0 01-.623.273.81.81 0 01-.623-.252L8.875 4.37v6.256a.847.847 0 01-.252.624.843.843 0 01-.623.25zM2.75 15c-.481 0-.893-.171-1.236-.514A1.682 1.682 0 011 13.25V8c0-.248.084-.456.252-.624a.843.843 0 01.623-.251c.248 0 .456.084.624.252A.843.843 0 012.75 8v5.25h10.5V8c0-.248.084-.456.252-.624a.843.843 0 01.623-.251c.248 0 .456.084.624.252A.843.843 0 0115 8v5.25c0 .481-.171.893-.514 1.236A1.682 1.682 0 0113.25 15H2.75z" />
    </g>
  ),
});
ShareArrowIcon.displayName = 'ShareArrowIcon';

export default ShareArrowIcon;
