/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShopifyIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_835:6)">
        <path d="M12.761.371l-1.02 3.597s-1.153-.5-2.522-.4c-2.013.125-2.013 1.3-2.013 1.599.108 1.599 4.643 1.948 4.911 5.72.188 2.973-1.69 4.996-4.4 5.146-3.275.2-5.073-1.599-5.073-1.599l.698-2.748S5.14 12.96 6.589 12.86c.94-.05 1.288-.774 1.261-1.274-.134-2.098-3.837-1.973-4.079-5.42C3.583 3.27 5.623.321 10.131.071c1.745-.125 2.63.3 2.63.3z"></path>
      </g>
      <defs>
        <clipPath id="clip0_835:6">
          <path d="M0 0h16v16H0z"></path>
        </clipPath>
      </defs>
    </g>
  ),
});
ShopifyIcon.displayName = 'ShopifyIcon';

export default ShopifyIcon;
