/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const ShortIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_3870_2347)">
        <path d="M10.784 6.011c-.22-.123-.43-.256-.68-.4.25-.151.479-.284.699-.408a2.732 2.732 0 001.415-2.815C11.97.515 9.798-.569 8.154.363c-1.683.96-3.367 1.902-5.03 2.89-1.32.79-1.512 1.836-1.301 3.072.134.77.65 1.34 1.33 1.73.238.134.468.267.726.42-.287.17-.545.323-.823.465a2.737 2.737 0 00-.956 3.623 2.787 2.787 0 003.758 1.132 392.887 392.887 0 004.352-2.492c.344-.2.708-.38 1.014-.627 1.54-1.274 1.31-3.585-.44-4.565zm-5.136 3.12V4.974l3.615 2.073L5.648 9.13z" />
      </g>
      <defs>
        <clipPath id="clip0_3870_2347">
          <path d="M0 0h14v14H0z" />
        </clipPath>
      </defs>
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
ShortIcon.displayName = 'ShortIcon'

export default ShortIcon
