/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const ShortIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_3870_2347)">
        <path d="M12.324 6.87c-.251-.141-.492-.293-.776-.456.284-.174.547-.326.798-.468a3.123 3.123 0 001.618-3.217C13.679.59 11.198-.65 9.319.415 7.395 1.513 5.47 2.588 3.569 3.719c-1.508.902-1.726 2.097-1.486 3.51.153.88.743 1.532 1.52 1.978.273.152.535.304.83.478-.328.196-.623.37-.94.532A3.128 3.128 0 002.4 14.358a3.185 3.185 0 004.295 1.293 453.05 453.05 0 004.973-2.847c.394-.228.81-.435 1.159-.717 1.76-1.457 1.497-4.097-.503-5.217zm-5.869 3.565v-4.75l4.131 2.37-4.13 2.38z" />
      </g>
      <defs>
        <clipPath id="clip0_3870_2347">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
});
ShortIcon.displayName = 'ShortIcon';

export default ShortIcon;
