/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const SidebarIcon = createIconComponent({
  content: (
    <g>
      <path d="M2 2a1 1 0 00-1 1v10a1 1 0 001 1h2a1 1 0 001-1V3a1 1 0 00-1-1H2zm6 0a1 1 0 00-1 1v10a1 1 0 001 1h6a1 1 0 001-1V3a1 1 0 00-1-1H8z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
SidebarIcon.displayName = 'SidebarIcon'

export default SidebarIcon
