/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SpamIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M4.9 3.208V3a3 3 0 013-3h.2a3 3 0 013 3v.208A3.001 3.001 0 0113 6v.3h1V3.8h2v2.5a2 2 0 01-2 2h-1v1.5h1a2 2 0 012 2v2.5h-2v-2.5h-1.064a5.001 5.001 0 01-9.872 0H2v2.5H0v-2.5a2 2 0 012-2h1V8.3H2a2 2 0 01-2-2V3.8h2v2.5h1V6a3 3 0 011.9-2.792zM6.9 3a1 1 0 011-1h.2a1 1 0 011 1H6.9zM5 6a1 1 0 011-1h4a1 1 0 011 1v1H5V6zm4 3h2v2a3.001 3.001 0 01-2 2.83V9zM7 9v4.83A3.001 3.001 0 015 11V9h2z"
        clipRule="evenodd"
      ></path>
    </g>
  ),
});
SpamIcon.displayName = 'SpamIcon';

export default SpamIcon;
