/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const StartPageIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3 1a1 1 0 00-1 1v12a1 1 0 001 1h10a1 1 0 001-1V2a1 1 0 00-1-1H3zm5 1.5a2 2 0 100 4 2 2 0 000-4zM3.333 9a1 1 0 011-1h7.334a1 1 0 110 2H4.333a1 1 0 01-1-1zm1 2a1 1 0 100 2h7.334a1 1 0 100-2H4.333z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
StartPageIcon.displayName = 'StartPageIcon'

export default StartPageIcon
