/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const StarOutlineIcon = createIconComponent({
  content: (
    <g>
      <g clipPath="url(#clip0_3728_2240)">
        <path
          fillRule="evenodd"
          d="M11.124 4.343L9.252.925c-.393-1.233-2.11-1.233-2.502 0L4.876 4.343l-3.572.749c-.66.005-1.1.467-1.244.94a1.345 1.345 0 00.458 1.464l2.54 3.14-.45 3.628a1.344 1.344 0 00.464 1.463c.415.32 1.05.402 1.572.01L8 14.11l3.356 1.628a1.288 1.288 0 001.572-.011c.41-.316.642-.88.462-1.466l-.694-3.625 2.784-3.139c.502-.387.604-.995.46-1.465-.145-.473-.584-.935-1.244-.94l-3.572-.749zm-4.989 1.71L8 2.61l1.865 3.441 3.744.736-2.91 3.218.713 3.649L8 11.963l-3.426 1.699.475-3.656-2.667-3.217 3.753-.737z"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="clip0_3728_2240">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </g>
  ),
});
StarOutlineIcon.displayName = 'StarOutlineIcon';

export default StarOutlineIcon;
