/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const StarOutlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M10.734 4.8l-1.64-2.99C8.751.73 7.25.73 6.906 1.81L5.266 4.8l-3.125.655a1.146 1.146 0 00-1.089.823c-.126.41-.036.942.401 1.281l2.223 2.748-.393 3.174a1.176 1.176 0 00.405 1.28c.363.28.918.352 1.375.01L8 13.346l2.937 1.425c.457.342 1.012.27 1.375-.01.358-.276.562-.77.405-1.283l-.608-3.172 2.436-2.746c.439-.338.529-.87.403-1.282a1.146 1.146 0 00-1.09-.823L10.735 4.8zM6.368 6.296L8 3.285l1.632 3.01 3.276.644-2.546 2.816.624 3.193L8 11.468l-2.998 1.486.416-3.199-2.333-2.814 3.283-.645z"
        clipRule="evenodd"
      />
    </g>
  ),
});
StarOutlineIcon.displayName = 'StarOutlineIcon';

export default StarOutlineIcon;
