/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const StatsIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2.5 8a1 1 0 011 1v3a1 1 0 11-2 0V9a1 1 0 011-1zM6 3a1 1 0 011 1v8a1 1 0 11-2 0V4a1 1 0 011-1zm3.5 2a1 1 0 011 1v6a1 1 0 11-2 0V6a1 1 0 011-1zM13 1a1 1 0 011 1v10a1 1 0 11-2 0V2a1 1 0 011-1z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
StatsIcon.displayName = 'StatsIcon'

export default StatsIcon
