/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SubheadingIcon = createIconComponent({
  content: (
    <g>
      <path d="M6.537 10.773H3.455l-.586 1.758H1L4.176 4h1.629l3.193 8.531h-1.87l-.59-1.758zM3.93 9.35h2.132L4.99 6.156 3.93 9.35zm9.427 3.181a1.881 1.881 0 01-.17-.568c-.41.457-.943.685-1.6.685-.62 0-1.136-.18-1.546-.539a1.737 1.737 0 01-.61-1.359c0-.672.249-1.188.745-1.547.5-.36 1.22-.54 2.162-.545h.78v-.363c0-.293-.077-.527-.23-.703-.148-.176-.384-.264-.708-.264-.285 0-.51.068-.674.205-.16.137-.24.324-.24.563H9.572c0-.367.114-.707.34-1.02.227-.312.547-.556.961-.732a3.47 3.47 0 011.395-.27c.78 0 1.4.197 1.857.592.46.39.691.941.691 1.652v2.748c.004.602.088 1.057.252 1.366v.1h-1.71zm-1.4-1.178c.25 0 .48-.054.691-.163.211-.114.368-.264.47-.452v-1.09h-.634c-.847 0-1.299.293-1.353.88l-.006.099c0 .21.074.385.223.521.148.137.351.206.609.206z" />
    </g>
  ),
});
SubheadingIcon.displayName = 'SubheadingIcon';

export default SubheadingIcon;
