/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SubheadingIcon = createIconComponent({
  content: (
    <g>
      <path d="M5.762 7.049H2.555l-.61 1.829H0L3.305 0H5l3.323 8.878H6.378l-.616-1.83zM3.05 5.567h2.22L4.151 2.244 3.05 5.567zm9.81 3.311a1.957 1.957 0 01-.177-.591c-.427.475-.982.713-1.665.713-.646 0-1.183-.187-1.61-.561a1.808 1.808 0 01-.634-1.415c0-.699.259-1.235.775-1.61.52-.373 1.27-.562 2.25-.566h.81V4.47c0-.305-.079-.55-.237-.732-.155-.183-.4-.275-.738-.275-.297 0-.53.072-.701.214-.167.142-.25.337-.25.585H8.92c0-.382.118-.736.353-1.06.236-.326.57-.58 1-.763a3.61 3.61 0 011.452-.28c.813 0 1.457.205 1.932.615.48.407.72.98.72 1.72v2.86c.004.626.091 1.1.262 1.42v.104h-1.78zm-1.458-1.226c.26 0 .5-.056.72-.17a1.16 1.16 0 00.488-.47V5.878h-.659c-.882 0-1.351.305-1.408.915l-.006.103c0 .22.077.4.231.543.155.142.366.213.634.213z" />
    </g>
  ),
});
SubheadingIcon.displayName = 'SubheadingIcon';

export default SubheadingIcon;
