
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const SwapIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M1.207 4a.5.5 0 0 1-.353-.854L3.646.354a.5.5 0 0 1 .708 0l2.792 2.792A.5.5 0 0 1 6.793 4H1.207zM5 4H3v3a1 1 0 1 0 2 0V4zm-2 6a1 1 0 0 1 2 0v1a1 1 0 1 1-2 0v-1zm11.793 2.207a.5.5 0 0 1 .353.854l-2.793 2.793a.5.5 0 0 1-.707 0L8.854 13.06a.5.5 0 0 1 .353-.854h5.586zm-3.793-3v3h2v-3a1 1 0 1 0-2 0zm2-3a1 1 0 0 1-2 0v-1a1 1 0 1 1 2 0v1z" />
    </g>
  ),
});
SwapIcon.displayName = 'SwapIcon';

export default SwapIcon;
