
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const TagIcon = createIconComponent({
  content: (
    <g>
      <path fillRule="evenodd" clipRule="evenodd" d="M14 1H8.414a1 1 0 0 0-.707.293l-7 7a1 1 0 0 0 0 1.414l5.586 5.586a1 1 0 0 0 1.414 0l7-7A1 1 0 0 0 15 7.586V2a1 1 0 0 0-1-1zm-2.5 5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
    </g>
  ),
});
TagIcon.displayName = 'TagIcon';

export default TagIcon;
