/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TagIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M14 1H8.414a1 1 0 00-.707.293l-7 7a1 1 0 000 1.414l5.586 5.586a1 1 0 001.414 0l7-7A1 1 0 0015 7.586V2a1 1 0 00-1-1zm-2.5 5a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
TagIcon.displayName = 'TagIcon'

export default TagIcon
