
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const TeamInboxIcon = createIconComponent({
  content: (
    <g>
      <path d="M1 12V8h4.652c0 3.23 4.848 3.23 4.848 0H15v4a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2z" />
      <path d="M5 6h6M6.5 4h3" />
      <path d="M1.5 10V7.5l1.3-4.764A.999.999 0 0 1 3.763 2h8.472a1 1 0 0 1 .965.737L14.5 7.5V10" />
    </g>
  ),
});
TeamInboxIcon.displayName = 'TeamInboxIcon';

export default TeamInboxIcon;
