/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TextItalicIcon = createIconComponent({
  content: (
    <g>
      <path d="M7.887 11.5l2.334-7H12a1 1 0 100-2H7a1 1 0 000 2h1.113l-2.334 7H4a1 1 0 100 2h5a1 1 0 000-2H7.887z" />
    </g>
  ),
})
TextItalicIcon.displayName = 'TextItalicIcon'

export default TextItalicIcon
