/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TextAlignCenterIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2.45 2a.95.95 0 000 1.9h11a.95.95 0 100-1.9h-11zm1.5 3.4a.95.95 0 000 1.9h8a.95.95 0 100-1.9h-8zM1.5 9.75a.95.95 0 01.95-.95h11a.95.95 0 110 1.9h-11a.95.95 0 01-.95-.95zm2.45 2.45a.95.95 0 100 1.9h8a.95.95 0 000-1.9h-8z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
TextAlignCenterIcon.displayName = 'TextAlignCenterIcon'

export default TextAlignCenterIcon
