/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const TextUnderlineIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M1.5 13.5a1 1 0 011-1h11a1 1 0 110 2h-11a1 1 0 01-1-1zM4 2a1 1 0 011 1v3.75a3 3 0 106 0V3a1 1 0 112 0v3.75a5 5 0 11-10 0V3a1 1 0 011-1z"
        clipRule="evenodd"
      />
    </g>
  ),
});
TextUnderlineIcon.displayName = 'TextUnderlineIcon';

export default TextUnderlineIcon;
