/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TextAlignRightIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M13.45 2a.95.95 0 110 1.9h-11a.95.95 0 010-1.9h11zm0 3.4a.95.95 0 110 1.9h-8a.95.95 0 010-1.9h8zm.95 4.35a.95.95 0 00-.95-.95h-11a.95.95 0 000 1.9h11a.95.95 0 00.95-.95zm-.95 2.45a.95.95 0 110 1.9h-8a.95.95 0 010-1.9h8z"
        clipRule="evenodd"
      />
    </g>
  ),
})
TextAlignRightIcon.displayName = 'TextAlignRightIcon'

export default TextAlignRightIcon
