/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TextExpandIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2.016 9.99a.675.675 0 000 1.35h3.968a.675.675 0 000-1.35H2.016zm0-2.351a.675.675 0 100 1.35h4.968a.675.675 0 000-1.35H2.016zm0-2.351a.675.675 0 100 1.35h11.968a.675.675 0 100-1.35H2.016zm0-2.35a.675.675 0 100 1.35h11.968a.675.675 0 100-1.35H2.016zM11.5 14.426a3.5 3.5 0 100-7 3.5 3.5 0 000 7zm2.139-3.5a.389.389 0 01-.389.389h-1.361v1.361a.389.389 0 01-.778 0v-1.361H9.75a.389.389 0 110-.778h1.361V9.176a.389.389 0 11.778 0v1.361h1.361c.215 0 .389.174.389.389z"
        clipRule="evenodd"
      />
    </g>
  ),
})
TextExpandIcon.displayName = 'TextExpandIcon'

export default TextExpandIcon
