/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const TextSummarizeIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M2.016 9.99a.675.675 0 000 1.35h3.968a.675.675 0 000-1.35H2.016zm0-2.351a.675.675 0 100 1.35h4.968a.675.675 0 000-1.35H2.016zm0-2.351a.675.675 0 100 1.35h11.968a.675.675 0 100-1.35H2.016zm0-2.35a.675.675 0 100 1.35h11.968a.675.675 0 100-1.35H2.016zM15 10.926a3.5 3.5 0 11-7 0 3.5 3.5 0 017 0zm-1.361 0a.389.389 0 01-.389.389h-3.5a.389.389 0 110-.778h3.5c.215 0 .389.174.389.389z"
        clipRule="evenodd"
      />
    </g>
  ),
});
TextSummarizeIcon.displayName = 'TextSummarizeIcon';

export default TextSummarizeIcon;
