/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const ThumbsupIcon = createIconComponent({
  content: (
    <g>
      <path d="M10.413 16c-2.177 0-5.602-.713-6.444-1.304a.7.7 0 01-.299-.574v-6.8a.7.7 0 01.263-.54c.053-.034 1.282-.99 2.564-1.704 1.598-.87 2.705-2.087 2.968-2.852C9.78 1.287 10.238 0 11.678 0c.684 0 1.246.383 1.545 1.043.597 1.357-.035 3.235-1.089 4.714.702.156 1.58.382 2.107.539.966.295 1.598.991 1.739 1.843.123.87-.316 1.757-1.247 2.435-.685 1.826-1.861 4.713-2.722 5.183-.333.173-.913.243-1.598.243zm-5.338-2.296c1.334.557 5.443 1.13 6.216.835.404-.365 1.44-2.695 2.16-4.66a.741.741 0 01.263-.349c.58-.382.878-.834.826-1.217-.053-.313-.334-.574-.755-.713-.878-.278-3.056-.748-3.09-.748a.716.716 0 01-.528-.47.645.645 0 01.158-.678c1.58-1.687 1.862-3.408 1.563-4.104-.07-.209-.158-.209-.21-.209-.352 0-.51.244-.879 1.287-.42 1.218-1.878 2.679-3.617 3.618-.843.452-1.686 1.06-2.107 1.374v6.034zm-1.775.487V7.235c0-.626-.509-1.13-1.141-1.13S1 6.608 1 7.234v6.939c0 .626.51 1.13 1.141 1.13.633 0 1.16-.504 1.16-1.113z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
ThumbsupIcon.displayName = 'ThumbsupIcon'

export default ThumbsupIcon
