/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const TiktokIcon = createIconComponent({
  content: (
    <g>
      <path d="M8.823 0H6.455v10.217c0 1.218-.91 2.218-2.044 2.218-1.133 0-2.043-1-2.043-2.218 0-1.195.89-2.174 1.983-2.217V5.435C1.943 5.478 0 7.587 0 10.217 0 12.87 1.983 15 4.432 15c2.448 0 4.431-2.152 4.431-4.783V4.978A5.26 5.26 0 0012 6.108V3.544C10.22 3.478 8.823 1.913 8.823 0z" />
    </g>
  ),
});
TiktokIcon.displayName = 'TiktokIcon';

export default TiktokIcon;
