/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TitleIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3.429 16h9.142c.632 0 1.143-.512 1.143-1.143V3.976c0-.341-.152-.664-.414-.881L9.876.262A1.143 1.143 0 009.148 0h-5.72c-.63 0-1.142.512-1.142 1.143v13.714c0 .631.511 1.143 1.143 1.143zM4 6.429c0-.395.32-.715.714-.715h6.572a.714.714 0 110 1.429H4.714A.714.714 0 014 6.429zm5.143-4.676v1.961c0 .158.128.286.286.286h2.353a.286.286 0 00.183-.505L9.611 1.533a.286.286 0 00-.468.22z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
TitleIcon.displayName = 'TitleIcon'

export default TitleIcon
