
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const TrashIcon = createIconComponent({
  content: (
    <g>
      <path d="M4.89 13.124L4 6h8l-.89 7.124a1 1 0 0 1-.993.876H5.883a1 1 0 0 1-.993-.876zM8 4H5a1 1 0 0 0-1 1h8a1 1 0 0 0-1-1H8z" />
      <path d="M7 4c0-1.333 2-1.333 2 0H7z" />
    </g>
  ),
});
TrashIcon.displayName = 'TrashIcon';

export default TrashIcon;
