/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const TrashIcon = createIconComponent({
  content: (
    <g>
      <path d="M3.91 14.1L3 5h10l-.91 9.1a1 1 0 01-.995.9h-6.19a1 1 0 01-.995-.9zM2 3a1 1 0 011-1h10a1 1 0 110 2H3a1 1 0 01-1-1zm5-1.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5V2H7v-.5z" />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
TrashIcon.displayName = 'TrashIcon'

export default TrashIcon
