/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const UnknownIcon = createIconComponent({
  content: (
    <g>
      <path d="M6.912 10.365c0-.804.098-1.444.293-1.92.195-.478.551-.946 1.068-1.405.523-.465.87-.842 1.043-1.129.172-.293.258-.6.258-.922 0-.97-.448-1.456-1.344-1.456-.425 0-.767.132-1.025.397-.253.258-.385.617-.396 1.077H4.31c.011-1.098.365-1.956 1.06-2.577.7-.62 1.654-.93 2.86-.93 1.218 0 2.163.296 2.835.887.672.586 1.008 1.416 1.008 2.49 0 .489-.11.95-.328 1.387-.218.431-.6.91-1.146 1.44l-.697.663c-.437.419-.687.91-.75 1.473l-.034.525H6.912zm-.25 2.645c0-.384.13-.7.388-.947.264-.253.6-.38 1.008-.38.408 0 .74.127 1 .38.263.247.396.563.396.947 0 .38-.13.693-.388.94-.253.247-.589.37-1.008.37-.42 0-.758-.123-1.017-.37a1.257 1.257 0 01-.379-.94z" />
    </g>
  ),
});
UnknownIcon.displayName = 'UnknownIcon';

export default UnknownIcon;
