/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const UnsplashIcon = createIconComponent({
  content: (
    <g>
      <path d="M5.219 4.797V1h5.062v3.797H5.22zm5.062 2.11H14.5V14.5H1V6.906h4.219v3.797h5.062V6.906z" />
    </g>
  ),
})
UnsplashIcon.displayName = 'UnsplashIcon'

export default UnsplashIcon
