/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react'
import createIconComponent from '../utils/createIconComponent'

const WarningIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 16A8 8 0 108 0a8 8 0 000 16zM7 4a1 1 0 012 0v5a1 1 0 11-2 0V4zm1 7a1 1 0 100 2 1 1 0 000-2z"
        clipRule="evenodd"
      />
    </g>
  ),
})
// @ts-expect-error TS(2339) FIXME: Property 'displayName' does not exist on type '(pr... Remove this comment to see the full error message
WarningIcon.displayName = 'WarningIcon'

export default WarningIcon
