
/** WARNING
 * This file is automatically generated by the `npm run gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from '../utils/createIconComponent';

const WhatsNewIcon = createIconComponent({
  content: (
    <g>
      <path d="M8 3S4 3 4 5.455c0 2.454.5 3.545 0 4.5C3.5 10.909 2 12 2 12h12s-1.486-1.053-2-2.045c-.808-1.561 0-2.743 0-4.5C12 3 8 3 8 3z" />
      <path d="M7 5c-1-3.5 3-3.5 2 0S7 5 7 5zM9 13.5c0 1.333-2 1.333-2 0h2z" />
    </g>
  ),
});
WhatsNewIcon.displayName = 'WhatsNewIcon';

export default WhatsNewIcon;
