"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.twitter = exports.pinterest = exports.linkedin = exports.instagram = exports.googleplus = exports.facebook = exports.grayShadow = exports.boxShadow = exports.grayDefault = exports.grayDarker = exports.grayDark = exports.gray = exports.grayLight = exports.grayLighter = exports.white = exports.green = exports.yellow = exports.orange = exports.redLight = exports.red = exports.teal = exports.pink = exports.purple = exports.blueLighter = exports.blueDarker = exports.blue = void 0;
var blue = '#2c4bff';
exports.blue = blue;
var blueDarker = '#1F35B3';
exports.blueDarker = blueDarker;
var blueLighter = '#6B81FF';
exports.blueLighter = blueLighter;
var purple = '#9C2BFF';
exports.purple = purple;
var pink = '#D925AC';
exports.pink = pink;
var teal = '#00C8CF';
exports.teal = teal;
var red = '#E0364F';
exports.red = red;
var redLight = '#FDF2F4';
exports.redLight = redLight;
var orange = '#FF702C';
exports.orange = orange;
var yellow = '#FADE2A';
exports.yellow = yellow;
var green = '#87C211';
exports.green = green;
var white = '#FFFFFF';
exports.white = white;
var grayLighter = '#F5F5F5';
exports.grayLighter = grayLighter;
var grayLight = '#E0E0E0';
exports.grayLight = grayLight;
var gray = '#B8B8B8';
exports.gray = gray;
var grayDark = '#636363';
exports.grayDark = grayDark;
var grayDarker = '#3D3D3D';
exports.grayDarker = grayDarker;
var grayDefault = '#77797a';
exports.grayDefault = grayDefault;
var boxShadow = '#ABB7FF';
exports.boxShadow = boxShadow;
var grayShadow = '0px 1px 4px rgba(0, 0, 0, 0.16)';
exports.grayShadow = grayShadow;
var facebook = '#3b5998';
exports.facebook = facebook;
var googleplus = '#dd4b39';
exports.googleplus = googleplus;
var instagram = '#e53c5f';
exports.instagram = instagram;
var linkedin = '#007bb6';
exports.linkedin = linkedin;
var pinterest = '#bd081c';
exports.pinterest = pinterest;
var twitter = '#55acee';
exports.twitter = twitter;