/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const ButtonLinkIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M1.5 3A1.5 1.5 0 000 4.5v7A1.5 1.5 0 001.5 13h13a1.5 1.5 0 001.5-1.5v-7A1.5 1.5 0 0014.5 3h-13zM4 7a1 1 0 000 2h8a1 1 0 100-2H4z"
        clipRule="evenodd"
      />
    </g>
  ),
});
ButtonLinkIcon.displayName = 'ButtonLinkIcon';

export default ButtonLinkIcon;
