/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const CalendarIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M4 0a1 1 0 011 1v1h6V1a1 1 0 112 0v1h1a1 1 0 011 1v11a1 1 0 01-1 1H2a1 1 0 01-1-1V3a1 1 0 011-1h1V1a1 1 0 011-1zM3 7v6h10V7H3z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CalendarIcon.displayName = 'CalendarIcon';

export default CalendarIcon;
