/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const CaretLeftIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M4.293 8.957a1 1 0 010-1.414l5.25-5.25a1 1 0 011.414 1.414L6.414 8.25l4.543 4.543a1 1 0 01-1.414 1.414l-5.25-5.25z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CaretLeftIcon.displayName = 'CaretLeftIcon';

export default CaretLeftIcon;
