/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const CaretUpIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M7.543 10.957a1 1 0 001.414 0l5.25-5.25a1 1 0 00-1.414-1.414L8.25 8.836 3.707 4.293a1 1 0 00-1.414 1.414l5.25 5.25z"
        clipRule="evenodd"
      />
    </g>
  ),
});
CaretUpIcon.displayName = 'CaretUpIcon';

export default CaretUpIcon;
