/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const CheckmarkIcon = createIconComponent({
  content: (
    <g>
      <path d="M3.06 8.146a1 1 0 000 1.415l2.83 2.828 7.07-7.071a1 1 0 10-1.414-1.414L5.889 9.56 4.475 8.146a1 1 0 00-1.414 0z" />
    </g>
  ),
});
CheckmarkIcon.displayName = 'CheckmarkIcon';

export default CheckmarkIcon;
