/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const DirectIcon = createIconComponent({
  content: (
    <g>
      <path d="M13.5 14.5a1 1 0 001-1v-11a1 1 0 00-1-1h-2v2h1v9h-1v2h2zM7.839 4.475l3.035 3.035a.5.5 0 010 .708L7.84 11.253a.5.5 0 01-.854-.354V8.864h-4.07a1 1 0 010-2h4.07V4.828a.5.5 0 01.854-.353z" />
    </g>
  ),
});
DirectIcon.displayName = 'DirectIcon';

export default DirectIcon;
