/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const HotkeysIcon = createIconComponent({
  content: (
    <g>
      <path d="M6 4H4v2h2V4zm1 0h2v2H7V4zm5 0h-2v2h2V4zM4 7h2v2H4V7zm5 0H7v2h2V7zm1 0h2v2h-2V7zm2 3H4v2h8v-2z" />
      <path
        fillRule="evenodd"
        d="M0 4a3 3 0 013-3h10a3 3 0 013 3v8a3 3 0 01-3 3H3a3 3 0 01-3-3V4zm3-1h10a1 1 0 011 1v8a1 1 0 01-1 1H3a1 1 0 01-1-1V4a1 1 0 011-1z"
        clipRule="evenodd"
      />
    </g>
  ),
});
HotkeysIcon.displayName = 'HotkeysIcon';

export default HotkeysIcon;
