/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const LockedIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3 7a1 1 0 00-1 1v7a1 1 0 001 1h10a1 1 0 001-1V8a1 1 0 00-1-1H3zm5 6a1 1 0 100-2 1 1 0 000 2zM8 3a3 3 0 00-3 3v1H3V6a5 5 0 0110 0v1h-2V6a3 3 0 00-3-3z"
        clipRule="evenodd"
      />
    </g>
  ),
});
LockedIcon.displayName = 'LockedIcon';

export default LockedIcon;
