/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const PhoneIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3 1a1 1 0 011-1h8a1 1 0 011 1v14a1 1 0 01-1 1H4a1 1 0 01-1-1V1zm2 1h6v11H5V2zm2.444 12c-.306 0-.555.224-.555.5s.249.5.555.5h1.112c.306 0 .555-.224.555-.5s-.249-.5-.555-.5H7.444z"
        clipRule="evenodd"
      />
    </g>
  ),
});
PhoneIcon.displayName = 'PhoneIcon';

export default PhoneIcon;
