/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const PinnedIcon = createIconComponent({
  content: (
    <g>
      <path d="M10.46 1.146c-.365-.364-.991-.09-.977.427l.115 1.433-4.737 3.397-2.273.137c-.489.036-.714.63-.37.975l2.53 2.53-2.686 2.686a.58.58 0 00-.117.168l-.66 1.437c-.11.24.136.486.376.376l1.437-.66a.58.58 0 00.168-.116l2.686-2.687 2.533 2.533c.344.344.938.12.975-.369l.14-2.283 3.393-4.733 1.427.114c.518.015.793-.612.429-.976l-4.39-4.39z" />
    </g>
  ),
});
PinnedIcon.displayName = 'PinnedIcon';

export default PinnedIcon;
