/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const SparklesIcon = createIconComponent({
  content: (
    <g>
      <path d="M6.589 6.993l-1.13 3.896-1.13-3.896L.514 5.84 4.33 4.685 5.459.79l1.13 3.895 3.814 1.154L6.59 6.993zm5.682 2.597l2.826-1.587-1.554 2.886 1.554 2.885-2.826-1.587-2.825 1.587L11 10.889 9.446 8.003l2.825 1.587zm-5.033 1.582l-1.2 2.164 1.2 2.164-2.119-1.226L3 15.5l1.2-2.164L3 11.172l2.119 1.226 2.119-1.226z" />
    </g>
  ),
});
SparklesIcon.displayName = 'SparklesIcon';

export default SparklesIcon;
