/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const SubstackIcon = createIconComponent({
  content: (
    <g>
      <path d="M13 6.121H3V4.703h10v1.418zM3 7.406V14l5-2.945L13 14V7.406H3zM13 2H3v1.418h10V2z" />
    </g>
  ),
});
SubstackIcon.displayName = 'SubstackIcon';

export default SubstackIcon;
