/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const SubtractIcon = createIconComponent({
  content: (
    <g>
      <path d="M13 9a1 1 0 100-2H3a1 1 0 000 2h10z" />
    </g>
  ),
});
SubtractIcon.displayName = 'SubtractIcon';

export default SubtractIcon;
