/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const TelegramIcon = createIconComponent({
  content: (
    <g>
      <path d="M1.1 7.708c4.295-1.871 7.159-3.105 8.592-3.7C13.783 2.305 14.633 2.01 15.188 2c.121-.002.394.028.57.171a.62.62 0 01.21.4c.02.114.044.375.025.58-.222 2.33-1.181 7.982-1.67 10.592-.206 1.104-.613 1.474-1.006 1.51-.856.079-1.505-.565-2.334-1.108-1.297-.85-2.03-1.38-3.288-2.209-1.455-.959-.512-1.485.317-2.346.217-.226 3.987-3.655 4.06-3.966.01-.038.018-.183-.069-.26-.086-.077-.213-.05-.305-.03-.13.03-2.201 1.4-6.214 4.108-.588.404-1.12.6-1.598.59-.526-.011-1.538-.297-2.29-.542-.923-.3-1.656-.458-1.592-.968.033-.265.398-.536 1.096-.814z" />
    </g>
  ),
});
TelegramIcon.displayName = 'TelegramIcon';

export default TelegramIcon;
