/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const UnlockedIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M3 7a1 1 0 00-1 1v7a1 1 0 001 1h10a1 1 0 001-1V8a1 1 0 00-1-1H3zm5 6a1 1 0 100-2 1 1 0 000 2zM5 6a3 3 0 015.332-1.888L12 3a5 5 0 00-9 3v1h2V6z"
        clipRule="evenodd"
      />
    </g>
  ),
});
UnlockedIcon.displayName = 'UnlockedIcon';

export default UnlockedIcon;
