/** WARNING
 * This file is automatically generated by the `yarn gen:icons` command.
 * ALL changes will be overwritten.
 */
import React from 'react';
import createIconComponent from './utils/createIconComponent';

const ViewIcon = createIconComponent({
  content: (
    <g>
      <path
        fillRule="evenodd"
        d="M8 13.5c4.418 0 8-5.5 8-5.5s-3.582-6-8-6-8 6-8 6 3.582 5.5 8 5.5zM8 11a3 3 0 100-6 3 3 0 000 6z"
        clipRule="evenodd"
      />
      <path d="M10 8a2 2 0 11-4 0 2 2 0 014 0z" />
    </g>
  ),
});
ViewIcon.displayName = 'ViewIcon';

export default ViewIcon;
